/**
 * The file_input capability END-TO-END through the REAL composition
 * root: it boots the greenfield FILE-only fixture (`__fixtures__/file-ingest.product.yaml` —
 * file_input, no audio/record/stt/agents) via `assembleServer` from `RAYSPEC_SPEC_PATH` on a
 * throwaway DATABASE + a real DBOS launch, and drives the byte surface over REAL HTTP against
 * MATERIALIZED ground truth (fail-the-fix):
 *
 *   (a) boot WITH blob env and WITHOUT RAYSPEC_MEDIA_SIGNING_KEY / STT_PROVIDER /
 *       RAYSPEC_EXTRACTION_MODE (the positive half of the env-demand law: a file-only doc
 *       demands the BLOB root ONLY — no file download in v1, so no media key) → both routes mount
 *       with their DECLARED action tuples (stream:ingest upload + handler submit);
 *   (b) upload → submit → the REAL DBOS workflow runs off-request → EXACTLY ONE `workflow_runs`
 *       row whose PK equals the INDEPENDENTLY-RECOMPUTED deterministic id over the C10 key
 *       `file_id:<id>` (pinning the whole enqueue-key derivation, not just a row count) → the
 *       declared store row carries the server-derived byte metadata → the bytes are ON DISK under
 *       the tenant-jailed content-addressed key;
 *   (c) byte-identical re-upload + re-submit → deduped, STILL one run (C10 single-flight);
 *   (d) divergent post-seal upload → 409 `file_conflict`, sealed bytes untouched, still one run
 *       (the heal re-emit dedups downstream);
 *   (e) oversize Content-Length → 413 BEFORE any byte is read: ZERO blob bytes, ZERO pointer row,
 *       ZERO runs; (f) disallowed mime → 415, zero side effects; (g) unauthenticated → 401;
 *   (h) cross-tenant: a SECOND org's submit hits the bridge sink's fail-closed assertion → a clean
 *       403 `file_event_rejected`, ZERO enqueue (runs unchanged);
 *   (i) erasure: the boot's `eraseTenantNow` control seam (gate ON via RAYSPEC_ERASURE_ENABLED)
 *       REALLY deletes tenant A's on-disk blob subtree + its `file_uploads`/`ingested_files` rows —
 *       and is TENANT-SCOPED: tenant B's blob + pointer row (the arm-(h) witness) stay UNTOUCHED.
 *
 * the `file_input.parse_text` step joined the fixture pipeline (upload → parse → the
 * extracted text lands in the declared store via `{artifact}` → the store-sourced view serves it):
 *   (b2) the extracted text is SERVED over HTTP by the declared view (GET /views/files/{file_id});
 *   (j)  a COMMITTED text-layer PDF (self-made fixture) parses end-to-end on the REAL pinned
 *        parser: run completes, the store row carries the extracted text, the view serves it;
 *   (k)  a no-text-layer PDF fails the workflow with the TYPED terminal error VISIBLE in the
 *        durable journal: `workflow_runs.status='terminal_failure'` + the parse node state's
 *        `error.code='scanned_pdf_no_text_layer'` — and ZERO store row (the honest v1 no-OCR cut).
 *
 * The negative env-demand half (a file-only doc WITHOUT RAYSPEC_BLOB_ROOT fail-closes naming
 * file_input) lives in product-boot-conditional-env.db.test.ts (no second DBOS launch there); the
 * zero-file-surface conditional for a NON-file doc is pinned there too (HTTP 404) + at the compose
 * layer. Skips without DATABASE_URL; the un-skippable ran-guard hard-fails a REQUIRED run.
 */
import { createHash } from 'node:crypto';
import { existsSync, mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { registerScopedTables } from '@rayspec/db/testing';
import { exportPKCS8, generateKeyPair } from 'jose';
import postgres from 'postgres';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { assembleServer, type BootedServer, loadServerConfig } from './composition-root.js';

const baseUrl = process.env.DATABASE_URL;
const here = dirname(fileURLToPath(import.meta.url));
const FILE_YAML = resolve(here, '__fixtures__/file-ingest.product.yaml');

const SUITE_DB = `rayspec_w2fi_file_${process.pid}`;
const TENANT = '00000000-0000-4000-8000-00000000f101';
const TENANT_B = '00000000-0000-4000-8000-00000000f102';
const FILE_ID = 'inv-001';
const BODY = 'vendor,total\nacme,42\n';
const BODY_SHA = createHash('sha256').update(BODY).digest('hex');
// The COMMITTED self-made PDF fixtures (generated by the product-yaml test-support
// builder; no downloaded/internet fixtures). text-layer.pdf carries exactly one text line;
// no-text-layer.pdf is a structurally valid PDF whose single page has an EMPTY content stream.
const PDF_FILE_ID = 'pdf-001';
const PDF_BYTES = new Uint8Array(readFileSync(join(here, '__fixtures__/text-layer.pdf')));
const PDF_SHA = createHash('sha256').update(PDF_BYTES).digest('hex');
const PDF_TEXT = 'Hello RaySpec PDF fixture.';
const SCAN_FILE_ID = 'scan-001';
const SCAN_BYTES = new Uint8Array(readFileSync(join(here, '__fixtures__/no-text-layer.pdf')));

// Ran-guard: skipIf(!baseUrl) must never let a REQUIRED run (CI /
// RAYSPEC_REQUIRE_DB_TESTS) read green after silently skipping this proof.
const dbRequired = Boolean(process.env.CI) || process.env.RAYSPEC_REQUIRE_DB_TESTS === 'true';
let e2eTestsRan = 0;

/**
 * The INDEPENDENT oracle for the durable run id (ids.ts `durableWorkflowRunId`, recomputed here on
 * purpose — a derivation/format drift re-keys durable runs on redelivery, so this test must go RED
 * on it rather than follow it): v5-shaped UUID over sha256(`${tenant}:${workflowId}:${key}`).
 */
function expectedRunId(tenantId: string, workflowId: string, idempotencyKey: string): string {
  const h = createHash('sha256')
    .update(`${tenantId}:${workflowId}:${idempotencyKey}`)
    .digest('hex');
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-5${h.slice(13, 16)}-8${h.slice(17, 20)}-${h.slice(20, 32)}`;
}

function adminUrl(url: string): string {
  const u = new URL(url);
  u.pathname = '/postgres';
  return u.toString();
}
function withDbName(url: string, name: string): string {
  const u = new URL(url);
  u.pathname = `/${name}`;
  return u.toString();
}

describe.skipIf(!baseUrl)('file-ingest — real boot + real DBOS + HTTP', () => {
  let server: BootedServer | undefined;
  let appDbUrl = '';
  let dbosSysDb = '';
  let blobDir = '';
  let tokenA = '';
  const saved: Record<string, string | undefined> = {};
  const ENV = [
    'RAYSPEC_JWT_SIGNING_KEY',
    'RAYSPEC_API_KEY_PEPPER',
    'DATABASE_URL',
    'ALLOWED_ORIGINS',
    'PORT',
    'RAYSPEC_SPEC_PATH',
    'DBOS_SYSTEM_DATABASE_URL',
    'RAYSPEC_PRODUCT_TENANT_ID',
    'RAYSPEC_EXTRACTION_MODE',
    'STT_PROVIDER',
    'RAYSPEC_BLOB_ROOT',
    'RAYSPEC_MEDIA_SIGNING_KEY',
    'RAYSPEC_ERASURE_ENABLED',
  ] as const;

  async function drop(admin: postgres.Sql): Promise<void> {
    await admin.unsafe(`DROP DATABASE IF EXISTS "${dbosSysDb}" WITH (FORCE)`);
    await admin.unsafe(`DROP DATABASE IF EXISTS "${SUITE_DB}" WITH (FORCE)`);
  }

  beforeAll(async () => {
    if (!baseUrl) return;
    appDbUrl = withDbName(baseUrl, SUITE_DB);
    dbosSysDb = `${SUITE_DB}_dbos_sys`;
    const admin = postgres(adminUrl(baseUrl), { max: 1 });
    try {
      await drop(admin);
      await admin.unsafe(`CREATE DATABASE "${SUITE_DB}"`);
    } finally {
      await admin.end();
    }

    blobDir = mkdtempSync(join(tmpdir(), 'rayspec-w2fi-'));
    for (const k of ENV) saved[k] = process.env[k];
    const { privateKey } = await generateKeyPair('RS256', { extractable: true });
    process.env.RAYSPEC_JWT_SIGNING_KEY = await exportPKCS8(privateKey);
    process.env.RAYSPEC_API_KEY_PEPPER = 'w2fi-file-pepper';
    process.env.DATABASE_URL = appDbUrl;
    delete process.env.ALLOWED_ORIGINS;
    process.env.PORT = '8808';
    process.env.RAYSPEC_SPEC_PATH = FILE_YAML;
    delete process.env.DBOS_SYSTEM_DATABASE_URL;
    process.env.RAYSPEC_PRODUCT_TENANT_ID = TENANT;
    // The blob root IS demanded (file_input moves bytes) — set it.
    process.env.RAYSPEC_BLOB_ROOT = blobDir;
    // The env-demand POSITIVE (arm a): a file-only doc must boot WITHOUT the media key (no file
    // download in v1 — RAYSPEC_MEDIA_SIGNING_KEY stays an AUDIO-only demand) and without stt/
    // extraction env. Deleting them makes the whole suite the proof: a demand regression aborts boot.
    delete process.env.RAYSPEC_MEDIA_SIGNING_KEY;
    delete process.env.STT_PROVIDER;
    delete process.env.RAYSPEC_EXTRACTION_MODE;
    // Arm (i): the operator erasure gate ON — eraseTenantNow must REALLY delete (dry-run otherwise).
    process.env.RAYSPEC_ERASURE_ENABLED = 'true';

    const config = loadServerConfig();
    server = await assembleServer(config, {
      registerProductTables: (tables) => registerScopedTables([...tables.values()]),
    });

    const client = postgres(appDbUrl, { max: 2 });
    try {
      await client.unsafe(
        `INSERT INTO orgs (id, name, slug) VALUES ($1, 'FilesA', 'files-a'), ($2, 'FilesB', 'files-b')`,
        [TENANT, TENANT_B],
      );
    } finally {
      await client.end();
    }
    tokenA = await tokenFor(TENANT);
  }, 180_000);

  afterAll(async () => {
    await server?.close();
    for (const k of ENV) {
      if (saved[k] === undefined) delete process.env[k];
      else process.env[k] = saved[k];
    }
    if (blobDir) rmSync(blobDir, { recursive: true, force: true });
    if (baseUrl) {
      const admin = postgres(adminUrl(baseUrl), { max: 1 });
      try {
        await drop(admin);
      } finally {
        await admin.end();
      }
    }
  }, 60_000);

  async function tokenFor(tenant: string): Promise<string> {
    const email = `w2fi-${tenant.slice(-4)}-${Date.now()}@example.com`;
    const reg = await server!.app.request('/v1/auth/register', {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({ email, password: 'a-long-enough-password' }),
    });
    expect([200, 201]).toContain(reg.status);
    const client = postgres(appDbUrl, { max: 2 });
    try {
      const rows = (await client.unsafe('SELECT id FROM users WHERE email = $1', [
        email,
      ])) as unknown as Array<{ id: string }>;
      await client.unsafe(
        `INSERT INTO memberships (org_id, user_id, role, status) VALUES ($1, $2, 'owner', 'active')`,
        [tenant, rows[0]!.id],
      );
    } finally {
      await client.end();
    }
    const sw = await server!.app.request(`/v1/orgs/${tenant}/switch`, {
      method: 'POST',
      headers: { authorization: `Bearer ${(await reg.json()).accessToken}` },
    });
    expect(sw.status).toBe(200);
    return (await sw.json()).accessToken as string;
  }

  /** PUT raw bytes — string OR binary (the in-process Request preserves a manual Content-Length). */
  function upload(
    fileId: string,
    body: string | Uint8Array,
    opts: {
      token?: string;
      contentType?: string;
      contentLength?: string;
      fileName?: string;
    } = {},
  ): Promise<Response> {
    const byteLength = typeof body === 'string' ? Buffer.byteLength(body) : body.byteLength;
    return server!.app.request(`/files/${fileId}`, {
      method: 'PUT',
      headers: {
        ...(opts.token ? { authorization: `Bearer ${opts.token}` } : {}),
        'content-type': opts.contentType ?? 'text/csv',
        'content-length': opts.contentLength ?? String(byteLength),
        ...(opts.fileName ? { 'x-file-name': opts.fileName } : {}),
      },
      body: body as BodyInit,
    });
  }

  function submit(fileId: string, token?: string, body: unknown = {}): Promise<Response> {
    return server!.app.request(`/files/${fileId}/submit`, {
      method: 'POST',
      headers: {
        'content-type': 'application/json',
        ...(token ? { authorization: `Bearer ${token}` } : {}),
      },
      body: JSON.stringify(body),
    });
  }

  async function workflowRuns(): Promise<Array<{ workflow_run_id: string; status: string }>> {
    const client = postgres(appDbUrl, { max: 1 });
    try {
      return (await client.unsafe(
        'SELECT workflow_run_id, status FROM workflow_runs',
      )) as unknown as Array<{ workflow_run_id: string; status: string }>;
    } finally {
      await client.end();
    }
  }
  async function ingestedRows(): Promise<Array<Record<string, unknown>>> {
    const client = postgres(appDbUrl, { max: 1 });
    try {
      return (await client.unsafe(
        'SELECT ingest_ref, file_id, sha256, size_bytes, content_type, extracted_text, status ' +
          'FROM ingested_files',
      )) as unknown as Array<Record<string, unknown>>;
    } finally {
      await client.end();
    }
  }
  /** The durable journal's parse node state for one run (arm (k) — the typed-error visibility). */
  async function parseNodeState(
    runId: string,
  ): Promise<{ status: string; error: { code?: string } | null } | undefined> {
    const client = postgres(appDbUrl, { max: 1 });
    try {
      const rows = (await client.unsafe(
        "SELECT status, error FROM workflow_node_states WHERE workflow_run_id = $1 AND node_id = 'parse'",
        [runId],
      )) as unknown as Array<{ status: string; error: { code?: string } | null }>;
      return rows[0];
    } finally {
      await client.end();
    }
  }
  /** Wait for ONE specific run to reach a TERMINAL status (completed / terminal_failure). */
  async function waitForRun(
    runId: string,
  ): Promise<{ workflow_run_id: string; status: string; error: { code?: string } | null }> {
    const deadline = Date.now() + 60_000;
    for (;;) {
      const client = postgres(appDbUrl, { max: 1 });
      try {
        const rows = (await client.unsafe(
          'SELECT workflow_run_id, status, error FROM workflow_runs WHERE workflow_run_id = $1',
          [runId],
        )) as unknown as Array<{
          workflow_run_id: string;
          status: string;
          error: { code?: string } | null;
        }>;
        const run = rows[0];
        if (run && (run.status === 'completed' || run.status === 'terminal_failure')) return run;
      } finally {
        await client.end();
      }
      if (Date.now() > deadline) throw new Error(`run ${runId} did not reach a terminal status`);
      await new Promise((r) => setTimeout(r, 250));
    }
  }
  async function pointerRows(): Promise<Array<Record<string, unknown>>> {
    const client = postgres(appDbUrl, { max: 1 });
    try {
      return (await client.unsafe(
        'SELECT file_id, file_ref, state, sha256 FROM file_uploads',
      )) as unknown as Array<Record<string, unknown>>;
    } finally {
      await client.end();
    }
  }
  /** The TENANT-scoped pointer rows (arm (i) — erasure must delete A's rows and ONLY A's). */
  async function pointerRowsFor(tenant: string): Promise<Array<Record<string, unknown>>> {
    const client = postgres(appDbUrl, { max: 1 });
    try {
      return (await client.unsafe(
        'SELECT file_id, file_ref, state, sha256 FROM file_uploads WHERE tenant_id = $1',
        [tenant],
      )) as unknown as Array<Record<string, unknown>>;
    } finally {
      await client.end();
    }
  }
  async function waitForCompletedRuns(
    expected: number,
  ): Promise<Array<{ workflow_run_id: string; status: string }>> {
    const deadline = Date.now() + 60_000;
    for (;;) {
      const runs = await workflowRuns();
      if (runs.length >= expected && runs.every((r) => r.status === 'completed')) return runs;
      if (Date.now() > deadline)
        throw new Error(`workflow did not complete: ${JSON.stringify(runs)}`);
      await new Promise((r) => setTimeout(r, 250));
    }
  }
  /** Assert run count stays `expected` across a short quiesce window (no late double-fire). */
  async function expectRunsQuiesced(expected: number): Promise<void> {
    const deadline = Date.now() + 2_000;
    for (;;) {
      expect(await workflowRuns()).toHaveLength(expected);
      if (Date.now() > deadline) break;
      await new Promise((r) => setTimeout(r, 250));
    }
  }

  const maybe = baseUrl ? it : it.skip;

  maybe(
    '(a) boot: file-only doc materializes WITHOUT media/stt/extraction env; both routes mount with their DECLARED tuples',
    () => {
      e2eTestsRan += 1;
      expect(server!.deployMode).toBe('materialized');
      const actions = server!.declaredRoutes.map((r) => `${r.method} ${r.path} → ${r.action}`);
      // WHOLE tuples through the boot surface: the upload is a stream/ingest route, the submit a
      // handler route — and nothing audio/record/media-shaped is mounted.
      expect(actions).toContain('PUT /files/{file_id} → stream:ingest.file_input_upload');
      expect(actions).toContain('POST /files/{file_id}/submit → handler:file_input_submit');
      // The declared store-sourced view mounts alongside the capability routes.
      expect(actions.some((a) => a.startsWith('GET /views/files/{file_id} → handler:'))).toBe(true);
      expect(actions.some((a) => a.includes('/sessions/') || a.includes('/records/'))).toBe(false);
    },
  );

  maybe(
    '(b) upload → submit → ONE durable run keyed file_id:<id> → the store row + the on-disk blob',
    async () => {
      e2eTestsRan += 1;
      const up = await upload(FILE_ID, BODY, { token: tokenA, fileName: 'invoice-march.csv' });
      expect(up.status).toBe(200);
      const upBody = (await up.json()) as Record<string, unknown>;
      expect(upBody).toMatchObject({
        file_id: FILE_ID,
        state: 'uploaded',
        sha256: BODY_SHA,
        size_bytes: Buffer.byteLength(BODY),
        replaced: false,
        deduped: false,
      });

      // GROUND TRUTH: the bytes sit under the tenant-jailed CONTENT-ADDRESSED key on disk.
      expect(existsSync(join(blobDir, TENANT, 'files', FILE_ID, BODY_SHA))).toBe(true);

      const sub = await submit(FILE_ID, tokenA);
      expect(sub.status).toBe(200);
      const subBody = (await sub.json()) as Record<string, unknown>;
      expect(subBody).toMatchObject({
        file_id: FILE_ID,
        event_id: `${TENANT}:${FILE_ID}`,
        deduped: false,
      });

      const runs = await waitForCompletedRuns(1);
      expect(runs).toHaveLength(1);
      // ★ THE C10 KEY PIN through the WHOLE composed stack: the durable run's PK must equal the
      // independently-recomputed deterministic id over the GENERIC `file_id:<id>` key (a key-format
      // drift — e.g. the audio ':finalized' suffix leaking in — re-keys durable runs → RED here).
      expect(runs[0]?.workflow_run_id).toBe(
        expectedRunId(TENANT, 'log_file', `file_id:${FILE_ID}`),
      );

      // MATERIALIZED ground truth: the declared store row carries the SERVER-derived byte metadata
      // AND the parse node's extracted text — the CSV passed through byte-exact via the
      // `{artifact}` value (upload → parse_text → store_write, end-to-end on the real DBOS path).
      const rows = await ingestedRows();
      expect(rows).toHaveLength(1);
      expect(rows[0]).toMatchObject({
        ingest_ref: FILE_ID,
        file_id: FILE_ID,
        sha256: BODY_SHA,
        size_bytes: Buffer.byteLength(BODY),
        content_type: 'text/csv',
        extracted_text: BODY,
        status: 'stored',
      });
    },
    120_000,
  );

  maybe(
    '(b2) the declared view SERVES the extracted text over HTTP (upload → parse → store → view)',
    async () => {
      e2eTestsRan += 1;
      const res = await server!.app.request(`/views/files/${FILE_ID}`, {
        headers: { authorization: `Bearer ${tokenA}` },
      });
      expect(res.status).toBe(200);
      expect(await res.json()).toEqual({
        file_id: FILE_ID,
        content_type: 'text/csv',
        extracted_text: BODY,
      });
    },
    60_000,
  );

  maybe(
    '(c) byte-identical re-upload + re-submit → deduped, STILL one run (C10)',
    async () => {
      e2eTestsRan += 1;
      const up = await upload(FILE_ID, BODY, { token: tokenA });
      expect(up.status).toBe(200);
      const upBody = (await up.json()) as Record<string, unknown>;
      expect(upBody).toMatchObject({ state: 'submitted', deduped: true, replaced: false });

      const sub = await submit(FILE_ID, tokenA);
      expect(sub.status).toBe(200);
      expect(((await sub.json()) as Record<string, unknown>).deduped).toBe(true);

      await expectRunsQuiesced(1);
      expect(await ingestedRows()).toHaveLength(1);
    },
    60_000,
  );

  maybe(
    '(d) divergent post-seal upload → 409, sealed bytes untouched, still one run',
    async () => {
      e2eTestsRan += 1;
      const up = await upload(FILE_ID, 'totally different bytes', { token: tokenA });
      expect(up.status).toBe(409);
      expect(((await up.json()) as Record<string, unknown>).error).toBe('file_conflict');

      // The sealed pointer row still names the ORIGINAL bytes (never silently replaced)…
      const pointers = await pointerRows();
      const sealed = pointers.find((p) => p.file_id === FILE_ID);
      expect(sealed).toMatchObject({ state: 'submitted', sha256: BODY_SHA });
      // …and the heal re-emit deduped downstream: STILL exactly one run.
      await expectRunsQuiesced(1);
    },
    60_000,
  );

  maybe(
    '(e) oversize Content-Length → 413 with ZERO blob bytes, ZERO pointer row, ZERO runs',
    async () => {
      e2eTestsRan += 1;
      // 25 MiB + 1 declared — the pre-check rejects BEFORE reading a byte (no huge body needed).
      const res = await upload('too-big', 'tiny', {
        token: tokenA,
        contentLength: String(25 * 1024 * 1024 + 1),
      });
      expect(res.status).toBe(413);
      expect(((await res.json()) as Record<string, unknown>).error).toBe('file_too_large');

      expect(existsSync(join(blobDir, TENANT, 'files', 'too-big'))).toBe(false);
      expect((await pointerRows()).some((p) => p.file_id === 'too-big')).toBe(false);
      await expectRunsQuiesced(1);
    },
    60_000,
  );

  maybe(
    '(f) disallowed mime → 415, zero side effects',
    async () => {
      e2eTestsRan += 1;
      const res = await upload('bad-mime', 'PKzipbytes', {
        token: tokenA,
        contentType: 'application/zip',
      });
      expect(res.status).toBe(415);
      expect(((await res.json()) as Record<string, unknown>).error).toBe('file_type_unsupported');

      expect(existsSync(join(blobDir, TENANT, 'files', 'bad-mime'))).toBe(false);
      expect((await pointerRows()).some((p) => p.file_id === 'bad-mime')).toBe(false);
      await expectRunsQuiesced(1);
    },
    60_000,
  );

  maybe(
    '(g) unauthenticated upload + submit → 401',
    async () => {
      e2eTestsRan += 1;
      expect((await upload('no-auth', 'x')).status).toBe(401);
      expect((await submit('no-auth')).status).toBe(401);
      await expectRunsQuiesced(1);
    },
    60_000,
  );

  maybe(
    "(h) cross-tenant: a SECOND org's submit is the sink's fail-closed 403, ZERO enqueue",
    async () => {
      e2eTestsRan += 1;
      const tokenB = await tokenFor(TENANT_B);
      // The upload lands under B's OWN server-derived tenant (tenant-jailed blob + tenant-scoped row).
      const up = await upload('b-file', 'tenant b bytes', { token: tokenB });
      expect(up.status).toBe(200);
      // The submit reaches the bridge sink, whose tenant assertion rejects fail-closed: the
      // dispatcher is bound to the DEPLOYMENT tenant (A), B's event must NEVER enqueue.
      const sub = await submit('b-file', tokenB);
      expect(sub.status).toBe(403);
      const body = (await sub.json()) as Record<string, unknown>;
      expect(body.error).toBe('file_event_rejected');
      expect(String(body.detail)).toContain('cross_tenant');
      // ZERO enqueue: the run set is unchanged (still only tenant A's single run).
      await expectRunsQuiesced(1);
      expect(await ingestedRows()).toHaveLength(1);
    },
    60_000,
  );

  maybe(
    '(j) a text-layer PDF parses END-TO-END on the REAL pinned parser: run completes, text in store + view',
    async () => {
      e2eTestsRan += 1;
      const up = await upload(PDF_FILE_ID, PDF_BYTES, {
        token: tokenA,
        contentType: 'application/pdf',
        fileName: 'fixture.pdf',
      });
      expect(up.status).toBe(200);
      expect(((await up.json()) as Record<string, unknown>).sha256).toBe(PDF_SHA);
      expect((await submit(PDF_FILE_ID, tokenA)).status).toBe(200);

      const run = await waitForRun(expectedRunId(TENANT, 'log_file', `file_id:${PDF_FILE_ID}`));
      expect(run.status).toBe('completed');

      // MATERIALIZED ground truth: the PDF text layer landed as the store row's extracted text…
      const row = (await ingestedRows()).find((r) => r.file_id === PDF_FILE_ID);
      expect(row).toMatchObject({
        ingest_ref: PDF_FILE_ID,
        sha256: PDF_SHA,
        content_type: 'application/pdf',
        extracted_text: PDF_TEXT,
        status: 'stored',
      });
      // …and the declared view serves it over HTTP.
      const res = await server!.app.request(`/views/files/${PDF_FILE_ID}`, {
        headers: { authorization: `Bearer ${tokenA}` },
      });
      expect(res.status).toBe(200);
      expect(((await res.json()) as Record<string, unknown>).extracted_text).toBe(PDF_TEXT);
    },
    120_000,
  );

  maybe(
    '(k) a no-text-layer PDF fails the workflow with the TYPED error VISIBLE in the durable journal',
    async () => {
      e2eTestsRan += 1;
      const up = await upload(SCAN_FILE_ID, SCAN_BYTES, {
        token: tokenA,
        contentType: 'application/pdf',
      });
      expect(up.status).toBe(200);
      expect((await submit(SCAN_FILE_ID, tokenA)).status).toBe(200);

      // The run reaches the TYPED terminal failure (never a hang/crash): the run header carries
      // terminal_failure, and the parse NODE state journals the named error code — the operator-
      // visible surface for "this PDF is a scan; v1 extracts text layers only" (the no-OCR cut).
      const runId = expectedRunId(TENANT, 'log_file', `file_id:${SCAN_FILE_ID}`);
      const run = await waitForRun(runId);
      expect(run.status).toBe('terminal_failure');
      const node = await parseNodeState(runId);
      expect(node?.status).toBe('terminal_failure');
      expect(node?.error?.code).toBe('scanned_pdf_no_text_layer');

      // Fail-closed downstream: NO store row materialized for the failed parse (the store_write
      // never ran), and the view honestly serves its declared ABSENT shape.
      expect((await ingestedRows()).some((r) => r.file_id === SCAN_FILE_ID)).toBe(false);
      const res = await server!.app.request(`/views/files/${SCAN_FILE_ID}`, {
        headers: { authorization: `Bearer ${tokenA}` },
      });
      expect(res.status).toBe(200);
      expect(((await res.json()) as Record<string, unknown>).extracted_text).toBeNull();
    },
    120_000,
  );

  maybe(
    "(i) erasure: eraseTenantNow(A) → A's blob subtree + rows GONE; B's data UNTOUCHED (tenant-scoped)",
    async () => {
      e2eTestsRan += 1;
      // Ground-truth BASELINE (assert-before-erase): A's sealed blobs (the CSV + both PDFs) +
      // rows AND B's cross-tenant witness (the arm-(h) upload — same literals) are all present on
      // disk / in the DB. A's rows: 3 pointer rows (inv-001, pdf-001, scan-001) but only 2 store
      // rows (the scanned PDF's workflow failed typed — arm (k) — so its store_write never ran).
      const bSha = createHash('sha256').update('tenant b bytes').digest('hex');
      expect(existsSync(join(blobDir, TENANT, 'files', FILE_ID, BODY_SHA))).toBe(true);
      expect(existsSync(join(blobDir, TENANT, 'files', PDF_FILE_ID, PDF_SHA))).toBe(true);
      expect(existsSync(join(blobDir, TENANT_B, 'files', 'b-file', bSha))).toBe(true);
      expect(await pointerRowsFor(TENANT)).toHaveLength(3);
      expect(await pointerRowsFor(TENANT_B)).toHaveLength(1);
      expect(await ingestedRows()).toHaveLength(2);

      // The boot's erasure control seam (operator gate ON in beforeAll): a REAL, tenant-scoped delete.
      const res = await server!.eraseTenantNow!(TENANT);
      expect(res.mode).toBe('deleted');
      expect(res.blobs).toBe('deleted');
      expect(res.tables).toEqual({ file_uploads: 3, ingested_files: 2 });

      // (a) A's blob is GONE on disk — the key AND the whole `<root>/<tenant>/` jail subtree.
      expect(existsSync(join(blobDir, TENANT, 'files', FILE_ID, BODY_SHA))).toBe(false);
      expect(existsSync(join(blobDir, TENANT))).toBe(false);
      // (b) A's file_uploads row(s) are gone — and the declared store row with them.
      expect(await pointerRowsFor(TENANT)).toHaveLength(0);
      expect(await ingestedRows()).toHaveLength(0);
      // (c) TENANT-SCOPED: B's data is untouched — blob still on disk, pointer row intact (arm (h)
      // SEALED it: the submit sets state 'submitted' BEFORE the sink's fail-closed 403).
      expect(existsSync(join(blobDir, TENANT_B, 'files', 'b-file', bSha))).toBe(true);
      const bRows = await pointerRowsFor(TENANT_B);
      expect(bRows).toHaveLength(1);
      expect(bRows[0]).toMatchObject({ file_id: 'b-file', state: 'submitted', sha256: bSha });
    },
    60_000,
  );
});

// The un-skippable ran-guard: fail loudly if a REQUIRED (CI / RAYSPEC_REQUIRE_DB_TESTS) run
// SKIPPED the file-ingest arms (a lost DATABASE_URL would otherwise read GREEN).
describe('file-ingest e2e — ran-guard', () => {
  it('all 12 e2e arms actually ran when the DB was required', () => {
    if (dbRequired) expect(e2eTestsRan).toBe(12);
    else expect(true).toBe(true);
  });
});
