/**
 * The supervisor's schema work against a real database as the migration role (supervisor.ts): the
 * steps an application process asks for in a boot's order bring the platform schema up, enable
 * row-level isolation on the product tables, apply the first product materialization — generated by
 * the supervisor from the document, never sent by the application — and migrate the workflow system
 * database, exactly as an in-process boot's `DeployApply` does. A delta the operator did not review
 * is refused before it touches the database, and nothing accepts a step after the work is done.
 *
 * Skips without DATABASE_URL; a required run fails the ran-guard.
 */
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { DeployError } from '@rayspec/api-auth';
import { createRuntimeRoleLane, type RuntimeRoleLane } from '@rayspec/db/testing';
import postgres from 'postgres';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import type { ServerConfig } from './composition-root.js';
import { FIRST_PRODUCT_MIGRATION, SchemaSteps, SupervisorProtocolError } from './supervisor.js';

const baseUrl = process.env.DATABASE_URL;
const dbRequired = Boolean(process.env.CI) || process.env.RAYSPEC_REQUIRE_DB_TESTS === 'true';

const SPEC = `version: '1.0'
metadata:
  name: schema-work
  id: schema-work-app
  version: '1.0.0'
stores:
  - name: sw_notes
    columns:
      - { name: body, type: text }
`;

function admin(url: string): string {
  const u = new URL(url);
  u.pathname = '/postgres';
  return u.toString();
}

describe.skipIf(!baseUrl)('the supervisor schema work, as the migration role', () => {
  const name = `rayspec_schema_work_${process.pid}`;
  const sysDb = `${name}_dbos_sys`;
  let lane: RuntimeRoleLane;
  let migrationUrl = '';
  let runtimeUrl = '';
  let migrationSysUrl = '';
  let specPath = '';
  let specDir = '';
  let ran = 0;

  beforeAll(async () => {
    if (!baseUrl) return;
    const server = postgres(admin(baseUrl), { max: 1, onnotice: () => {} });
    try {
      for (const db of [name, sysDb])
        await server.unsafe(`DROP DATABASE IF EXISTS "${db}" WITH (FORCE)`);
      await server.unsafe(`CREATE DATABASE "${name}"`);
    } finally {
      await server.end();
    }
    lane = createRuntimeRoleLane();
    const withDb = (db: string) => {
      const u = new URL(baseUrl as string);
      u.pathname = `/${db}`;
      return u.toString();
    };
    const app = await lane.prepare(withDb(name), 'application');
    const sys = await lane.prepare(withDb(sysDb), 'workflow-system');
    if (app === undefined || sys === undefined) throw new Error('the role lane was not prepared');
    migrationUrl = app.migration;
    runtimeUrl = app.runtime;
    migrationSysUrl = sys.migration;
    specDir = mkdtempSync(join(tmpdir(), 'schema-work-'));
    specPath = join(specDir, 'rayspec.yaml');
    writeFileSync(specPath, SPEC);
  }, 120_000);

  afterAll(async () => {
    if (specDir) rmSync(specDir, { recursive: true, force: true });
    await lane?.drop().catch(() => {});
    const server = postgres(admin(baseUrl ?? ''), { max: 1, onnotice: () => {} });
    try {
      for (const db of [name, sysDb])
        await server.unsafe(`DROP DATABASE IF EXISTS "${db}" WITH (FORCE)`);
    } catch {
      // best effort
    } finally {
      await server.end();
    }
    if (dbRequired) expect(ran).toBe(2);
  }, 60_000);

  const config = (): ServerConfig =>
    ({
      databaseUrl: runtimeUrl,
      migrationDatabaseUrl: migrationUrl,
      migrationDbosSystemDatabaseUrl: migrationSysUrl,
      specPath,
    }) as ServerConfig;

  async function withAdmin<T>(db: string, fn: (sql: postgres.Sql) => Promise<T>): Promise<T> {
    const u = new URL(baseUrl as string);
    u.pathname = `/${db}`;
    const sql = postgres(u.toString(), { max: 1, onnotice: () => {} });
    try {
      return await fn(sql);
    } finally {
      await sql.end();
    }
  }

  it('runs the boot steps in order and leaves the platform, product and workflow schema in place', async () => {
    const steps = new SchemaSteps({ config: config(), warn: () => {} });
    await steps.run({ type: 'request', id: 1, step: 'before-schema-change', facts: {} });
    await steps.run({ type: 'request', id: 2, step: 'platform-chain' });
    await steps.run({ type: 'request', id: 3, step: 'tenant-isolation' });
    await steps.run({
      type: 'request',
      id: 4,
      step: 'product-migration',
      name: FIRST_PRODUCT_MIGRATION,
    });
    await steps.run({ type: 'request', id: 5, step: 'workflow-system-schema' });
    await steps.run({ type: 'request', id: 6, step: 'schema-done' });
    expect(steps.done).toBe(true);

    // The platform tables and the product table exist; the product table is under forced row security
    // and is owned by the migration role, not the runtime role — exactly the in-process boot's result.
    const runtimeRole = decodeURIComponent(new URL(runtimeUrl).username);
    const [notes] = await withAdmin(name, (sql) =>
      sql.unsafe(
        `SELECT c.relrowsecurity, c.relforcerowsecurity, pg_get_userbyid(c.relowner) AS owner
           FROM pg_class c WHERE c.relname = 'sw_notes'`,
      ),
    );
    expect(notes).toMatchObject({ relrowsecurity: true, relforcerowsecurity: true });
    expect((notes as { owner: string }).owner).not.toBe(runtimeRole);
    const [orgs] = await withAdmin(name, (sql) =>
      sql.unsafe("SELECT to_regclass('public.orgs') IS NOT NULL AS present"),
    );
    expect((orgs as { present: boolean }).present).toBe(true);
    const [ledger] = await withAdmin(name, (sql) =>
      sql.unsafe('SELECT count(*)::int AS n FROM product_migration_ledger'),
    );
    expect((ledger as { n: number }).n).toBe(1);
    // The workflow system database was migrated by the migration role.
    const [sys] = await withAdmin(sysDb, (sql) =>
      sql.unsafe(
        "SELECT count(*)::int AS n FROM information_schema.schemata WHERE schema_name = 'dbos'",
      ),
    );
    expect((sys as { n: number }).n).toBeGreaterThan(0);

    // The migration connection is closed once the work is done: a step after it is refused.
    await expect(
      steps.run({ type: 'request', id: 7, step: 'platform-chain' }),
    ).rejects.toBeInstanceOf(SupervisorProtocolError);
    ran += 1;
  }, 120_000);

  it('refuses an unreviewed destructive delta before it touches the database', async () => {
    const steps = new SchemaSteps({
      config: config(),
      warn: () => {},
      updateMigrations: [{ name: 'drop.sql', sql: 'DROP TABLE sw_notes;', allowlist: [] }],
    });
    await steps.run({ type: 'request', id: 1, step: 'platform-chain' });
    await steps.run({ type: 'request', id: 2, step: 'tenant-isolation' });
    const before = await withAdmin(name, (sql) =>
      sql.unsafe("SELECT to_regclass('public.sw_notes') IS NOT NULL AS present"),
    );
    await expect(
      steps.run({ type: 'request', id: 3, step: 'product-migration', name: 'drop.sql' }),
    ).rejects.toBeInstanceOf(DeployError);
    const after = await withAdmin(name, (sql) =>
      sql.unsafe("SELECT to_regclass('public.sw_notes') IS NOT NULL AS present"),
    );
    expect(after).toEqual(before);
    await steps.close();
    ran += 1;
  }, 120_000);
});

describe('the supervisor schema work — ran-guard', () => {
  it('fails a required run that could not reach the database', () => {
    if (dbRequired && !baseUrl) throw new Error('schema-work: DATABASE_URL is required (CI)');
    expect(true).toBe(true);
  });
});
