/**
 * Renders `src/schemas.gen.ts` from the contract files. Shared by `scripts/gen-schemas.ts`, which
 * writes it, and `schemas.test.ts`, which checks the committed module is current.
 */
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

/** Module constant name, source file under `contract/`, and a JSON pointer into it. */
export const SCHEMA_SOURCES: readonly [string, string, string][] = [
  ['RAY_MANIFEST_SCHEMA', 'ray-manifest.schema.json', ''],
  ['SNAPSHOT_SCHEMA', 'snapshot.schema.json', ''],
  ['MANAGED_RECEIPT_SCHEMA', 'managed-receipt.schema.json', ''],
  ['RELEASE_MANIFEST_SCHEMA', 'release-manifest.schema.json', ''],
  ['BUNDLE_SIGNATURE_FILE_SCHEMA', 'cli-verbs.json', '/signatureFileSchema'],
  ['RESULT_ENVELOPE_SCHEMA', 'cli-verbs.json', '/envelopeSchema'],
  ['BINDINGS_FILE_SCHEMA', 'reserved-bindings.json', '/bindingsFile/schema'],
];

export function loadSchemaSource(contractDir: string, file: string, pointer: string): unknown {
  let node: unknown = JSON.parse(readFileSync(join(contractDir, file), 'utf8'));
  for (const part of pointer.split('/').slice(1)) node = (node as Record<string, unknown>)[part];
  return node;
}

export function renderSchemasModule(contractDir: string): string {
  const lines = [
    '// Generated by scripts/gen-schemas.ts from the committed files under contract/. Do not edit;',
    '// run `pnpm --filter @rayspec/bundle-contract gen:schemas` after a contract change.',
    '',
  ];
  for (const [name, file, pointer] of SCHEMA_SOURCES) {
    const schema = loadSchemaSource(contractDir, file, pointer);
    lines.push(`/** contract/${file}${pointer === '' ? '' : `#${pointer}`} */`);
    lines.push(
      `export const ${name}: Readonly<Record<string, unknown>> = ${JSON.stringify(schema, null, 2)};`,
      '',
    );
  }
  return lines.join('\n');
}
