// Generated by scripts/gen-schemas.ts from the committed files under contract/. Do not edit;
// run `pnpm --filter @rayspec/bundle-contract gen:schemas` after a contract change.

/** contract/ray-manifest.schema.json */
export const RAY_MANIFEST_SCHEMA: Readonly<Record<string, unknown>> = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "urn:rayspec:bundle:v1",
  "$comment": "RAY-CLOUD shared contract 1.0.0-draft.2. Validates ray.json, the root manifest of a .ray bundle (formatVersion 1). Structural only: the semantic rules in 06-SEMANTIC-DETAILS.md are normative and must also be enforced.",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "formatVersion": {
      "const": 1
    },
    "kind": {
      "enum": [
        "application",
        "migration"
      ]
    },
    "application": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": {
          "$ref": "#/$defs/applicationId"
        },
        "version": {
          "$ref": "#/$defs/exactVersion"
        }
      },
      "required": [
        "id",
        "version"
      ]
    },
    "runtime": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "version": {
          "$ref": "#/$defs/exactVersion"
        }
      },
      "required": [
        "version"
      ]
    },
    "target": {
      "$ref": "#/$defs/target"
    },
    "spec": {
      "allOf": [
        {
          "$ref": "#/$defs/payloadPath"
        },
        {
          "type": "string",
          "pattern": "[.]ya?ml$"
        }
      ]
    },
    "requires": {
      "type": "array",
      "maxItems": 128,
      "uniqueItems": true,
      "items": {
        "$ref": "#/$defs/capabilityId"
      }
    },
    "bindings": {
      "type": "array",
      "maxItems": 256,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "name": {
            "$ref": "#/$defs/bindingName"
          },
          "kind": {
            "enum": [
              "secret",
              "config"
            ]
          },
          "required": {
            "type": "boolean"
          },
          "description": {
            "type": "string",
            "minLength": 1,
            "maxLength": 1024
          }
        },
        "required": [
          "name",
          "kind",
          "required",
          "description"
        ]
      }
    },
    "permissions": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "egressHosts": {
          "type": "array",
          "maxItems": 256,
          "uniqueItems": true,
          "items": {
            "$ref": "#/$defs/egressHost"
          }
        },
        "execution": {
          "enum": [
            "none",
            "in-process",
            "sandboxed"
          ]
        }
      },
      "required": [
        "egressHosts",
        "execution"
      ]
    },
    "productMigration": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "fromProductSchemaDigest": {
          "$ref": "#/$defs/sha256"
        },
        "toProductSchemaDigest": {
          "$ref": "#/$defs/sha256"
        },
        "deltaPath": {
          "allOf": [
            {
              "$ref": "#/$defs/payloadPath"
            },
            {
              "type": "string",
              "pattern": "^payload/migrations/[A-Za-z0-9_.@+-]+[.]sql$"
            }
          ]
        },
        "allowlistPath": {
          "allOf": [
            {
              "$ref": "#/$defs/payloadPath"
            },
            {
              "type": "string",
              "pattern": "^payload/migrations/[A-Za-z0-9_.@+-]+[.]json$"
            }
          ]
        },
        "destructive": {
          "type": "boolean"
        }
      },
      "required": [
        "fromProductSchemaDigest",
        "toProductSchemaDigest",
        "deltaPath",
        "destructive"
      ]
    },
    "inventory": {
      "type": "array",
      "minItems": 1,
      "maxItems": 9999,
      "items": {
        "$ref": "#/$defs/inventoryEntry"
      }
    },
    "migration": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "encryption": {
          "const": "age-v1-x25519"
        },
        "ciphertextPath": {
          "const": "payload/migration.age"
        }
      },
      "required": [
        "encryption",
        "ciphertextPath"
      ]
    }
  },
  "required": [
    "formatVersion",
    "kind",
    "application",
    "runtime",
    "target",
    "inventory"
  ],
  "allOf": [
    {
      "if": {
        "properties": {
          "kind": {
            "const": "application"
          }
        },
        "required": [
          "kind"
        ],
        "type": "object"
      },
      "then": {
        "required": [
          "spec",
          "requires",
          "bindings",
          "permissions"
        ],
        "properties": {
          "spec": true,
          "requires": true,
          "bindings": true,
          "permissions": true,
          "migration": false
        },
        "type": "object"
      },
      "else": {
        "required": [
          "migration"
        ],
        "properties": {
          "inventory": {
            "maxItems": 1,
            "type": "array"
          },
          "spec": false,
          "requires": false,
          "bindings": false,
          "permissions": false,
          "productMigration": false,
          "migration": true
        },
        "type": "object"
      }
    }
  ],
  "$defs": {
    "sha256": {
      "type": "string",
      "pattern": "^[a-f0-9]{64}$"
    },
    "exactVersion": {
      "type": "string",
      "maxLength": 128,
      "pattern": "^(0|[1-9][0-9]*)[.](0|[1-9][0-9]*)[.](0|[1-9][0-9]*)(?:-(?:0|[1-9][0-9]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*)(?:[.](?:0|[1-9][0-9]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*))*)?$"
    },
    "applicationId": {
      "type": "string",
      "pattern": "^[a-z][a-z0-9-]{0,62}$"
    },
    "capabilityId": {
      "type": "string",
      "maxLength": 64,
      "pattern": "^[a-z][a-z0-9]*(?:[-_][a-z0-9]+)*$"
    },
    "bindingName": {
      "type": "string",
      "pattern": "^[A-Z][A-Z0-9_]{0,127}$"
    },
    "egressHost": {
      "type": "string",
      "maxLength": 253,
      "pattern": "^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?[.])+(?:[a-z]{2,63}|xn--[a-z0-9-]{0,58}[a-z0-9])$"
    },
    "payloadPath": {
      "type": "string",
      "maxLength": 4096,
      "pattern": "^(?!.*(?:^|/)[.]{1,2}(?:/|$))payload(?:/[A-Za-z0-9_.@+-]+)+$"
    },
    "target": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "os": {
          "type": "string",
          "pattern": "^[a-z][a-z0-9]{0,15}$"
        },
        "arch": {
          "type": "string",
          "pattern": "^[a-z][a-z0-9_]{0,15}$"
        },
        "nodeMajor": {
          "type": "integer",
          "minimum": 1,
          "maximum": 999
        }
      },
      "required": [
        "os",
        "arch",
        "nodeMajor"
      ]
    },
    "inventoryEntry": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "path": {
          "$ref": "#/$defs/payloadPath"
        },
        "size": {
          "type": "integer",
          "minimum": 0,
          "maximum": 4294967294
        },
        "sha256": {
          "$ref": "#/$defs/sha256"
        }
      },
      "required": [
        "path",
        "size",
        "sha256"
      ]
    }
  }
};

/** contract/snapshot.schema.json */
export const SNAPSHOT_SCHEMA: Readonly<Record<string, unknown>> = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "urn:rayspec:snapshot:v1",
  "$comment": "RAY-CLOUD shared contract 1.0.0-draft.2. Validates snapshot.json, the root of the inner encrypted snapshot archive (snapshotFormatVersion 1). The object index inside the snapshot (payload/object-index.json) validates against #/$defs/objectIndex; payload/objects.bin is the concatenation of the stored blob files in object-index order, one stored range per object, consecutive from offset 0 with no gaps or overlaps. The semantic rules in 06-SEMANTIC-DETAILS.md are normative and must also be enforced.",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "snapshotFormatVersion": {
      "const": 1
    },
    "sourceRuntime": {
      "$ref": "#/$defs/exactVersion"
    },
    "exportToolVersion": {
      "$ref": "#/$defs/exactVersion"
    },
    "applicationId": {
      "type": "string",
      "pattern": "^[a-z][a-z0-9-]{0,62}$"
    },
    "applicationVersion": {
      "$ref": "#/$defs/exactVersion"
    },
    "applicationDigest": {
      "$ref": "#/$defs/sha256"
    },
    "schemaHead": {
      "$ref": "#/$defs/schemaHead"
    },
    "databaseMajor": {
      "type": "integer",
      "minimum": 14,
      "maximum": 99
    },
    "fenceEpoch": {
      "type": "integer",
      "minimum": 1,
      "maximum": 9007199254740991
    },
    "capturedAt": {
      "$ref": "#/$defs/utcTimestamp"
    },
    "applicationTenantCount": {
      "const": 1
    },
    "workflowSystemDatabase": {
      "enum": [
        "included",
        "absent"
      ]
    },
    "runHistoryPolicy": {
      "enum": [
        "included",
        "excluded"
      ]
    },
    "identityPolicy": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "userIds": {
          "const": "preserved"
        },
        "passwordHashes": {
          "enum": [
            "preserved",
            "reset"
          ]
        },
        "sessions": {
          "const": "reset"
        },
        "apiKeys": {
          "const": "reset"
        },
        "invites": {
          "const": "reset"
        },
        "oidcArtifacts": {
          "const": "reset"
        },
        "jwtSigningKey": {
          "const": "reissued"
        },
        "apiKeyPepper": {
          "const": "reissued"
        },
        "mediaSigningKey": {
          "const": "reissued"
        },
        "mediaPlaybackTokens": {
          "const": "invalidated"
        }
      },
      "required": [
        "userIds",
        "passwordHashes",
        "sessions",
        "apiKeys",
        "invites",
        "oidcArtifacts",
        "jwtSigningKey",
        "apiKeyPepper",
        "mediaSigningKey",
        "mediaPlaybackTokens"
      ]
    },
    "tableCounts": {
      "type": "array",
      "maxItems": 10000,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "database": {
            "enum": [
              "application",
              "workflow-system"
            ]
          },
          "schema": {
            "type": "string",
            "pattern": "^[a-z_][a-z0-9_]{0,62}$"
          },
          "table": {
            "type": "string",
            "pattern": "^[a-z_][a-z0-9_]{0,62}$"
          },
          "rows": {
            "type": "integer",
            "minimum": 0,
            "maximum": 9007199254740991
          }
        },
        "required": [
          "database",
          "schema",
          "table",
          "rows"
        ]
      }
    },
    "objectCount": {
      "type": "integer",
      "minimum": 0,
      "maximum": 9007199254740991
    },
    "inventory": {
      "type": "array",
      "minItems": 4,
      "maxItems": 5,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "path": {
            "enum": [
              "payload/application.ray",
              "payload/database.dump",
              "payload/workflow-system.dump",
              "payload/object-index.json",
              "payload/objects.bin"
            ]
          },
          "size": {
            "type": "integer",
            "minimum": 0,
            "maximum": 4294967294
          },
          "sha256": {
            "$ref": "#/$defs/sha256"
          }
        },
        "required": [
          "path",
          "size",
          "sha256"
        ]
      },
      "allOf": [
        {
          "contains": {
            "properties": {
              "path": {
                "const": "payload/application.ray"
              }
            },
            "required": [
              "path"
            ],
            "type": "object"
          },
          "type": "array",
          "maxContains": 1
        },
        {
          "contains": {
            "properties": {
              "path": {
                "const": "payload/database.dump"
              }
            },
            "required": [
              "path"
            ],
            "type": "object"
          },
          "type": "array",
          "maxContains": 1
        },
        {
          "contains": {
            "properties": {
              "path": {
                "const": "payload/object-index.json"
              }
            },
            "required": [
              "path"
            ],
            "type": "object"
          },
          "type": "array",
          "maxContains": 1
        },
        {
          "contains": {
            "properties": {
              "path": {
                "const": "payload/objects.bin"
              }
            },
            "required": [
              "path"
            ],
            "type": "object"
          },
          "type": "array",
          "maxContains": 1
        }
      ]
    },
    "excludedDataCategories": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "$ref": "#/$defs/dataCategory"
      },
      "allOf": [
        {
          "contains": {
            "const": "credential-state"
          },
          "type": "array"
        },
        {
          "contains": {
            "const": "request-replay-state"
          },
          "type": "array"
        },
        {
          "contains": {
            "const": "security-audit-log"
          },
          "type": "array"
        },
        {
          "contains": {
            "const": "runtime-control-state"
          },
          "type": "array"
        }
      ]
    }
  },
  "required": [
    "snapshotFormatVersion",
    "sourceRuntime",
    "exportToolVersion",
    "applicationId",
    "applicationVersion",
    "applicationDigest",
    "schemaHead",
    "databaseMajor",
    "fenceEpoch",
    "capturedAt",
    "applicationTenantCount",
    "workflowSystemDatabase",
    "runHistoryPolicy",
    "identityPolicy",
    "tableCounts",
    "objectCount",
    "inventory",
    "excludedDataCategories"
  ],
  "allOf": [
    {
      "if": {
        "properties": {
          "workflowSystemDatabase": {
            "const": "included"
          }
        },
        "required": [
          "workflowSystemDatabase"
        ],
        "type": "object"
      },
      "then": {
        "properties": {
          "inventory": {
            "contains": {
              "properties": {
                "path": {
                  "const": "payload/workflow-system.dump"
                }
              },
              "required": [
                "path"
              ],
              "type": "object"
            },
            "type": "array",
            "maxContains": 1
          }
        },
        "type": "object"
      },
      "else": {
        "properties": {
          "inventory": {
            "not": {
              "contains": {
                "properties": {
                  "path": {
                    "const": "payload/workflow-system.dump"
                  }
                },
                "required": [
                  "path"
                ],
                "type": "object"
              },
              "type": "array"
            }
          }
        },
        "type": "object"
      }
    },
    {
      "if": {
        "properties": {
          "runHistoryPolicy": {
            "const": "excluded"
          }
        },
        "required": [
          "runHistoryPolicy"
        ],
        "type": "object"
      },
      "then": {
        "properties": {
          "excludedDataCategories": {
            "contains": {
              "const": "run-history"
            },
            "type": "array"
          }
        },
        "type": "object"
      },
      "else": {
        "properties": {
          "excludedDataCategories": {
            "not": {
              "contains": {
                "const": "run-history"
              },
              "type": "array"
            }
          }
        },
        "type": "object"
      }
    }
  ],
  "$defs": {
    "sha256": {
      "type": "string",
      "pattern": "^[a-f0-9]{64}$"
    },
    "exactVersion": {
      "type": "string",
      "maxLength": 128,
      "pattern": "^(0|[1-9][0-9]*)[.](0|[1-9][0-9]*)[.](0|[1-9][0-9]*)(?:-(?:0|[1-9][0-9]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*)(?:[.](?:0|[1-9][0-9]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*))*)?$"
    },
    "utcTimestamp": {
      "type": "string",
      "pattern": "^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](?:[.][0-9]{1,9})?Z$"
    },
    "schemaHead": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "platform": {
          "type": "string",
          "pattern": "^[0-9]{4}_[a-z0-9_]{1,120}$"
        },
        "product": {
          "$ref": "#/$defs/sha256"
        }
      },
      "required": [
        "platform",
        "product"
      ]
    },
    "dataCategory": {
      "enum": [
        "identity-and-tenancy",
        "credential-state",
        "request-replay-state",
        "run-history",
        "security-audit-log",
        "application-event-log",
        "platform-migration-ledger",
        "runtime-control-state",
        "product-store-data",
        "workflow-system-state",
        "blob-objects"
      ]
    },
    "objectIndex": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "objectIndexFormatVersion": {
          "const": 1
        },
        "objects": {
          "type": "array",
          "maxItems": 500000,
          "items": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "tenantId": {
                "type": "string",
                "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
              },
              "key": {
                "type": "string",
                "minLength": 1,
                "maxLength": 1024
              },
              "contentType": {
                "type": "string",
                "minLength": 1,
                "maxLength": 255
              },
              "size": {
                "type": "integer",
                "minimum": 0,
                "maximum": 4294967294
              },
              "sha256": {
                "$ref": "#/$defs/sha256"
              },
              "storedOffset": {
                "type": "integer",
                "minimum": 0,
                "maximum": 4294967294
              },
              "storedSize": {
                "type": "integer",
                "minimum": 0,
                "maximum": 4294967294
              },
              "storedSha256": {
                "$ref": "#/$defs/sha256"
              }
            },
            "required": [
              "tenantId",
              "key",
              "size",
              "sha256",
              "storedOffset",
              "storedSize",
              "storedSha256"
            ]
          }
        }
      },
      "required": [
        "objectIndexFormatVersion",
        "objects"
      ]
    }
  }
};

/** contract/managed-receipt.schema.json */
export const MANAGED_RECEIPT_SCHEMA: Readonly<Record<string, unknown>> = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "urn:rayspec:managed-receipt:v1",
  "$comment": "RAY-CLOUD shared contract 1.0.0-draft.2. A release capability receipt names exactly which public-hosting protections were tested for one runtime release. It is not a compliance certificate. Every const below is a protection the release must have tested; a release that cannot attest one of them has no managed receipt. supportedBackends and capabilities list only what the managed posture allows: capabilities.json ids whose managedPosture is self-host-only or test-only are refused here, and Cloud also cross-checks every listed id against capabilities.json managedPosture allowed.",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "receiptFormatVersion": {
      "const": 1
    },
    "contractVersion": {
      "const": "1.0.0-draft.2"
    },
    "runtimeVersion": {
      "$ref": "#/$defs/exactVersion"
    },
    "sourceCommit": {
      "type": "string",
      "pattern": "^[a-f0-9]{40}$"
    },
    "releaseManifestSha256": {
      "$ref": "#/$defs/sha256"
    },
    "artifactSha256": {
      "$ref": "#/$defs/sha256"
    },
    "targets": {
      "type": "array",
      "minItems": 1,
      "uniqueItems": true,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "os": {
            "const": "linux"
          },
          "arch": {
            "const": "x64"
          },
          "nodeMajor": {
            "const": 22
          },
          "nodeVersion": {
            "type": "string",
            "pattern": "^22[.](2[1-9]|[3-9][0-9]|[1-9][0-9]{2,})[.](0|[1-9][0-9]*)$"
          }
        },
        "required": [
          "os",
          "arch",
          "nodeMajor",
          "nodeVersion"
        ]
      }
    },
    "capabilityVocabularyVersion": {
      "const": 1
    },
    "capabilities": {
      "type": "array",
      "uniqueItems": true,
      "maxItems": 128,
      "items": {
        "type": "string",
        "maxLength": 64,
        "pattern": "^[a-z][a-z0-9]*(?:[-_][a-z0-9]+)*$",
        "not": {
          "enum": [
            "agent-backend-anthropic",
            "agent-backend-codex",
            "agent-backend-pi",
            "extraction-deterministic",
            "stt-fake",
            "tts-fake"
          ]
        }
      }
    },
    "maxApplicationTenants": {
      "const": 1
    },
    "singleTenantModeEnforced": {
      "const": true
    },
    "publicHostingPosture": {
      "const": "isolated-environment-v1"
    },
    "supportedBackends": {
      "type": "array",
      "minItems": 1,
      "uniqueItems": true,
      "items": {
        "enum": [
          "openai"
        ]
      }
    },
    "executionLevels": {
      "type": "array",
      "minItems": 1,
      "uniqueItems": true,
      "items": {
        "enum": [
          "none",
          "in-process"
        ]
      }
    },
    "databaseIsolation": {
      "const": "dedicated-db-and-rls"
    },
    "databaseRoleSeparation": {
      "const": true
    },
    "crossProcessCancellation": {
      "const": true
    },
    "agentTraceExport": {
      "const": "off"
    },
    "recoveryScopeEndpoint": {
      "enum": [
        "authenticated",
        "disabled"
      ]
    },
    "trustedProxiesPinned": {
      "const": true
    },
    "egressEnforcement": {
      "const": "host-network-policy"
    },
    "evidence": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "protection": {
            "type": "string",
            "minLength": 1,
            "maxLength": 128
          },
          "reference": {
            "type": "string",
            "minLength": 1,
            "maxLength": 2048
          },
          "sha256": {
            "$ref": "#/$defs/sha256"
          }
        },
        "required": [
          "protection",
          "reference",
          "sha256"
        ]
      }
    },
    "residualRisks": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "risk": {
            "type": "string",
            "minLength": 1,
            "maxLength": 2048
          },
          "owner": {
            "type": "string",
            "minLength": 1,
            "maxLength": 256
          }
        },
        "required": [
          "risk",
          "owner"
        ]
      }
    }
  },
  "required": [
    "receiptFormatVersion",
    "contractVersion",
    "runtimeVersion",
    "sourceCommit",
    "releaseManifestSha256",
    "artifactSha256",
    "targets",
    "capabilityVocabularyVersion",
    "capabilities",
    "maxApplicationTenants",
    "singleTenantModeEnforced",
    "publicHostingPosture",
    "supportedBackends",
    "executionLevels",
    "databaseIsolation",
    "databaseRoleSeparation",
    "crossProcessCancellation",
    "agentTraceExport",
    "recoveryScopeEndpoint",
    "trustedProxiesPinned",
    "egressEnforcement",
    "evidence",
    "residualRisks"
  ],
  "$defs": {
    "sha256": {
      "type": "string",
      "pattern": "^[a-f0-9]{64}$"
    },
    "exactVersion": {
      "type": "string",
      "maxLength": 128,
      "pattern": "^(0|[1-9][0-9]*)[.](0|[1-9][0-9]*)[.](0|[1-9][0-9]*)(?:-(?:0|[1-9][0-9]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*)(?:[.](?:0|[1-9][0-9]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*))*)?$"
    }
  }
};

/** contract/release-manifest.schema.json */
export const RELEASE_MANIFEST_SCHEMA: Readonly<Record<string, unknown>> = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "urn:rayspec:release-manifest:v1",
  "$comment": "RAY-CLOUD shared contract 1.0.0-draft.2. Validates the signed release manifest, the release catalog of one RaySpec release. The file is canonical JSON (01-RAY-BUNDLE.md) followed by one LF; releaseManifestSha256 is the SHA-256 of exactly those file bytes. Its detached signature file validates against #/$defs/signatureFile. The semantic rules in 06-SEMANTIC-DETAILS.md \"Release and bindings\" are normative and must also be enforced.",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "releaseManifestFormatVersion": {
      "const": 1
    },
    "rayspecVersion": {
      "$ref": "#/$defs/exactVersion"
    },
    "sourceCommit": {
      "type": "string",
      "pattern": "^[a-f0-9]{40}$"
    },
    "identityManifestSha256": {
      "$ref": "#/$defs/sha256"
    },
    "targets": {
      "type": "array",
      "minItems": 1,
      "maxItems": 16,
      "uniqueItems": true,
      "items": {
        "$ref": "#/$defs/target"
      }
    },
    "packages": {
      "type": "array",
      "minItems": 1,
      "maxItems": 256,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "name": {
            "type": "string",
            "pattern": "^(?:rayspec|@rayspec/[a-z0-9][a-z0-9-]{0,62})$"
          },
          "version": {
            "$ref": "#/$defs/exactVersion"
          },
          "integrity": {
            "type": "string",
            "pattern": "^sha512-[A-Za-z0-9+/]{86}==$"
          }
        },
        "required": [
          "name",
          "version",
          "integrity"
        ]
      }
    },
    "images": {
      "type": "array",
      "minItems": 1,
      "maxItems": 16,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "target": {
            "$ref": "#/$defs/target"
          },
          "platform": {
            "type": "string",
            "pattern": "^[a-z0-9]{1,16}/[a-z0-9]{1,16}$"
          },
          "nodeVersion": {
            "type": "string",
            "pattern": "^(0|[1-9][0-9]*)[.](0|[1-9][0-9]*)[.](0|[1-9][0-9]*)$"
          },
          "repository": {
            "type": "string",
            "maxLength": 255,
            "pattern": "^ghcr[.]io(?:/[a-z0-9]+(?:(?:[._]|__|-+)[a-z0-9]+)*)+$"
          },
          "digest": {
            "type": "string",
            "pattern": "^sha256:[a-f0-9]{64}$"
          }
        },
        "required": [
          "target",
          "platform",
          "nodeVersion",
          "repository",
          "digest"
        ]
      }
    }
  },
  "required": [
    "releaseManifestFormatVersion",
    "rayspecVersion",
    "sourceCommit",
    "identityManifestSha256",
    "targets",
    "packages",
    "images"
  ],
  "$defs": {
    "sha256": {
      "type": "string",
      "pattern": "^[a-f0-9]{64}$"
    },
    "exactVersion": {
      "type": "string",
      "maxLength": 128,
      "pattern": "^(0|[1-9][0-9]*)[.](0|[1-9][0-9]*)[.](0|[1-9][0-9]*)(?:-(?:0|[1-9][0-9]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*)(?:[.](?:0|[1-9][0-9]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*))*)?$"
    },
    "target": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "os": {
          "type": "string",
          "pattern": "^[a-z][a-z0-9]{0,15}$"
        },
        "arch": {
          "type": "string",
          "pattern": "^[a-z][a-z0-9_]{0,15}$"
        },
        "nodeMajor": {
          "type": "integer",
          "minimum": 1,
          "maximum": 999
        }
      },
      "required": [
        "os",
        "arch",
        "nodeMajor"
      ]
    },
    "signatureFile": {
      "$comment": "The detached signature of a release manifest, canonical JSON plus LF, by convention <manifest file>.sig. signature is standard base64 (with padding) of the 64-byte Ed25519 signature over the ASCII bytes \"rayspec-release-manifest-v1\\nsha256:<releaseManifestSha256>\\n\", made with the release key.",
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "signatureFormatVersion": {
          "const": 1
        },
        "algorithm": {
          "const": "ed25519"
        },
        "releaseManifestSha256": {
          "$ref": "#/$defs/sha256"
        },
        "publicKeySha256": {
          "$ref": "#/$defs/sha256"
        },
        "signature": {
          "type": "string",
          "pattern": "^[A-Za-z0-9+/]{86}==$"
        }
      },
      "required": [
        "signatureFormatVersion",
        "algorithm",
        "releaseManifestSha256",
        "publicKeySha256",
        "signature"
      ]
    }
  }
};

/** contract/cli-verbs.json#/signatureFileSchema */
export const BUNDLE_SIGNATURE_FILE_SCHEMA: Readonly<Record<string, unknown>> = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "urn:rayspec:bundle-signature:v1",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "signatureFormatVersion": {
      "const": 1
    },
    "algorithm": {
      "const": "ed25519"
    },
    "archiveSha256": {
      "type": "string",
      "pattern": "^[a-f0-9]{64}$"
    },
    "publicKeySha256": {
      "type": "string",
      "pattern": "^[a-f0-9]{64}$"
    },
    "signature": {
      "type": "string",
      "pattern": "^[A-Za-z0-9+/]{86}==$"
    }
  },
  "required": [
    "signatureFormatVersion",
    "algorithm",
    "archiveSha256",
    "publicKeySha256",
    "signature"
  ]
};

/** contract/cli-verbs.json#/envelopeSchema */
export const RESULT_ENVELOPE_SCHEMA: Readonly<Record<string, unknown>> = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "urn:rayspec:cli-envelope:v1",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "contractVersion": {
      "const": "1.0.0-draft.2"
    },
    "ok": {
      "type": "boolean"
    },
    "operation": {
      "enum": [
        "pack",
        "bundle.inspect",
        "bundle.verify",
        "bundle.sign",
        "deploy.dry-run",
        "deploy",
        "export",
        "import.dry-run",
        "import",
        "resume",
        "runtime.inspect",
        "runtime.prepare",
        "runtime.quiesce",
        "runtime.snapshot",
        "runtime.apply",
        "runtime.health",
        "runtime.resume",
        "init",
        "doctor",
        "plan",
        "openapi",
        "gen-handler",
        "deploy.legacy",
        "tenant.ensure",
        "dev.gen-secrets",
        "dev.db",
        "dev.bootstrap-tenant",
        "version",
        "help"
      ]
    },
    "operationId": {
      "type": "string",
      "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
    },
    "data": {},
    "errors": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/error"
      },
      "maxItems": 1000
    },
    "warnings": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/warning"
      },
      "maxItems": 1000
    }
  },
  "required": [
    "contractVersion",
    "ok",
    "operation",
    "operationId",
    "data",
    "errors",
    "warnings"
  ],
  "allOf": [
    {
      "if": {
        "type": "object",
        "properties": {
          "operation": {
            "const": "pack"
          }
        },
        "required": [
          "operation"
        ]
      },
      "then": {
        "type": "object",
        "properties": {
          "data": {
            "oneOf": [
              {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                  "outputPath": {
                    "oneOf": [
                      {
                        "type": "string",
                        "minLength": 1,
                        "maxLength": 4096
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "preview": {
                    "type": "boolean"
                  },
                  "sha256": {
                    "oneOf": [
                      {
                        "type": "string",
                        "pattern": "^[a-f0-9]{64}$"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "size": {
                    "oneOf": [
                      {
                        "type": "integer",
                        "minimum": 0,
                        "maximum": 9007199254740991
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "applicationId": {
                    "type": "string",
                    "pattern": "^[a-z][a-z0-9-]{0,62}$"
                  },
                  "applicationVersion": {
                    "type": "string",
                    "maxLength": 128,
                    "pattern": "^(0|[1-9][0-9]*)[.](0|[1-9][0-9]*)[.](0|[1-9][0-9]*)(?:-(?:0|[1-9][0-9]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*)(?:[.](?:0|[1-9][0-9]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*))*)?$"
                  },
                  "runtimeVersion": {
                    "type": "string",
                    "maxLength": 128,
                    "pattern": "^(0|[1-9][0-9]*)[.](0|[1-9][0-9]*)[.](0|[1-9][0-9]*)(?:-(?:0|[1-9][0-9]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*)(?:[.](?:0|[1-9][0-9]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*))*)?$"
                  },
                  "target": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                      "os": {
                        "type": "string",
                        "pattern": "^[a-z][a-z0-9]{0,15}$"
                      },
                      "arch": {
                        "type": "string",
                        "pattern": "^[a-z][a-z0-9_]{0,15}$"
                      },
                      "nodeMajor": {
                        "type": "integer",
                        "minimum": 1,
                        "maximum": 999
                      }
                    },
                    "required": [
                      "os",
                      "arch",
                      "nodeMajor"
                    ]
                  },
                  "requires": {
                    "type": "array",
                    "items": {
                      "type": "string",
                      "maxLength": 64,
                      "pattern": "^[a-z][a-z0-9]*(?:[-_][a-z0-9]+)*$"
                    },
                    "uniqueItems": true
                  },
                  "bindings": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "additionalProperties": false,
                      "properties": {
                        "name": {
                          "type": "string",
                          "pattern": "^[A-Z][A-Z0-9_]{0,127}$"
                        },
                        "kind": {
                          "enum": [
                            "secret",
                            "config"
                          ]
                        },
                        "required": {
                          "type": "boolean"
                        }
                      },
                      "required": [
                        "name",
                        "kind",
                        "required"
                      ]
                    }
                  },
                  "execution": {
                    "enum": [
                      "none",
                      "in-process",
                      "sandboxed"
                    ]
                  },
                  "egressHosts": {
                    "type": "array",
                    "items": {
                      "type": "string",
                      "maxLength": 253
                    },
                    "uniqueItems": true
                  },
                  "inclusion": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "additionalProperties": false,
                      "properties": {
                        "path": {
                          "type": "string",
                          "maxLength": 4096
                        },
                        "size": {
                          "type": "integer",
                          "minimum": 0,
                          "maximum": 9007199254740991
                        },
                        "sha256": {
                          "type": "string",
                          "pattern": "^[a-f0-9]{64}$"
                        },
                        "source": {
                          "type": "string",
                          "maxLength": 4096
                        }
                      },
                      "required": [
                        "path",
                        "size",
                        "sha256",
                        "source"
                      ]
                    },
                    "maxItems": 9999
                  }
                },
                "required": [
                  "outputPath",
                  "preview",
                  "sha256",
                  "size",
                  "applicationId",
                  "applicationVersion",
                  "runtimeVersion",
                  "target",
                  "requires",
                  "bindings",
                  "execution",
                  "egressHosts",
                  "inclusion"
                ]
              },
              {
                "type": "null"
              }
            ]
          }
        }
      }
    },
    {
      "if": {
        "type": "object",
        "properties": {
          "operation": {
            "const": "bundle.inspect"
          }
        },
        "required": [
          "operation"
        ]
      },
      "then": {
        "type": "object",
        "properties": {
          "data": {
            "oneOf": [
              {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                  "sha256": {
                    "type": "string",
                    "pattern": "^[a-f0-9]{64}$"
                  },
                  "size": {
                    "type": "integer",
                    "minimum": 0,
                    "maximum": 9007199254740991
                  },
                  "entries": {
                    "type": "integer",
                    "minimum": 0,
                    "maximum": 9007199254740991
                  },
                  "kind": {
                    "enum": [
                      "application",
                      "migration"
                    ]
                  },
                  "applicationId": {
                    "type": "string",
                    "pattern": "^[a-z][a-z0-9-]{0,62}$"
                  },
                  "applicationVersion": {
                    "type": "string",
                    "maxLength": 128,
                    "pattern": "^(0|[1-9][0-9]*)[.](0|[1-9][0-9]*)[.](0|[1-9][0-9]*)(?:-(?:0|[1-9][0-9]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*)(?:[.](?:0|[1-9][0-9]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*))*)?$"
                  },
                  "runtimeVersion": {
                    "type": "string",
                    "maxLength": 128,
                    "pattern": "^(0|[1-9][0-9]*)[.](0|[1-9][0-9]*)[.](0|[1-9][0-9]*)(?:-(?:0|[1-9][0-9]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*)(?:[.](?:0|[1-9][0-9]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*))*)?$"
                  },
                  "target": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                      "os": {
                        "type": "string",
                        "pattern": "^[a-z][a-z0-9]{0,15}$"
                      },
                      "arch": {
                        "type": "string",
                        "pattern": "^[a-z][a-z0-9_]{0,15}$"
                      },
                      "nodeMajor": {
                        "type": "integer",
                        "minimum": 1,
                        "maximum": 999
                      }
                    },
                    "required": [
                      "os",
                      "arch",
                      "nodeMajor"
                    ]
                  },
                  "requires": {
                    "type": "array",
                    "items": {
                      "type": "string",
                      "maxLength": 64,
                      "pattern": "^[a-z][a-z0-9]*(?:[-_][a-z0-9]+)*$"
                    },
                    "uniqueItems": true
                  },
                  "bindings": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "additionalProperties": false,
                      "properties": {
                        "name": {
                          "type": "string",
                          "pattern": "^[A-Z][A-Z0-9_]{0,127}$"
                        },
                        "kind": {
                          "enum": [
                            "secret",
                            "config"
                          ]
                        },
                        "required": {
                          "type": "boolean"
                        }
                      },
                      "required": [
                        "name",
                        "kind",
                        "required"
                      ]
                    }
                  },
                  "execution": {
                    "enum": [
                      "none",
                      "in-process",
                      "sandboxed",
                      null
                    ]
                  },
                  "egressHosts": {
                    "type": "array",
                    "items": {
                      "type": "string",
                      "maxLength": 253
                    },
                    "uniqueItems": true
                  },
                  "signature": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                      "present": {
                        "type": "boolean"
                      },
                      "verified": {
                        "type": "boolean"
                      },
                      "publicKeySha256": {
                        "oneOf": [
                          {
                            "type": "string",
                            "pattern": "^[a-f0-9]{64}$"
                          },
                          {
                            "type": "null"
                          }
                        ]
                      }
                    },
                    "required": [
                      "present",
                      "verified",
                      "publicKeySha256"
                    ]
                  },
                  "verdict": {
                    "enum": [
                      "structurally-valid",
                      "invalid"
                    ]
                  }
                },
                "required": [
                  "sha256",
                  "size",
                  "entries",
                  "kind",
                  "applicationId",
                  "applicationVersion",
                  "runtimeVersion",
                  "target",
                  "requires",
                  "bindings",
                  "execution",
                  "egressHosts",
                  "signature",
                  "verdict"
                ]
              },
              {
                "type": "null"
              }
            ]
          }
        }
      }
    },
    {
      "if": {
        "type": "object",
        "properties": {
          "operation": {
            "const": "bundle.verify"
          }
        },
        "required": [
          "operation"
        ]
      },
      "then": {
        "type": "object",
        "properties": {
          "data": {
            "oneOf": [
              {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                  "sha256": {
                    "type": "string",
                    "pattern": "^[a-f0-9]{64}$"
                  },
                  "kind": {
                    "enum": [
                      "application",
                      "migration"
                    ]
                  },
                  "applicationId": {
                    "type": "string",
                    "pattern": "^[a-z][a-z0-9-]{0,62}$"
                  },
                  "applicationVersion": {
                    "type": "string",
                    "maxLength": 128,
                    "pattern": "^(0|[1-9][0-9]*)[.](0|[1-9][0-9]*)[.](0|[1-9][0-9]*)(?:-(?:0|[1-9][0-9]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*)(?:[.](?:0|[1-9][0-9]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*))*)?$"
                  },
                  "runtimeVersion": {
                    "type": "string",
                    "maxLength": 128,
                    "pattern": "^(0|[1-9][0-9]*)[.](0|[1-9][0-9]*)[.](0|[1-9][0-9]*)(?:-(?:0|[1-9][0-9]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*)(?:[.](?:0|[1-9][0-9]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*))*)?$"
                  },
                  "checkedAgainstRuntime": {
                    "type": "string",
                    "maxLength": 128,
                    "pattern": "^(0|[1-9][0-9]*)[.](0|[1-9][0-9]*)[.](0|[1-9][0-9]*)(?:-(?:0|[1-9][0-9]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*)(?:[.](?:0|[1-9][0-9]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*))*)?$"
                  },
                  "signature": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                      "present": {
                        "type": "boolean"
                      },
                      "verified": {
                        "type": "boolean"
                      },
                      "publicKeySha256": {
                        "oneOf": [
                          {
                            "type": "string",
                            "pattern": "^[a-f0-9]{64}$"
                          },
                          {
                            "type": "null"
                          }
                        ]
                      }
                    },
                    "required": [
                      "present",
                      "verified",
                      "publicKeySha256"
                    ]
                  },
                  "verdict": {
                    "enum": [
                      "deployable",
                      "not-deployable"
                    ]
                  }
                },
                "required": [
                  "sha256",
                  "kind",
                  "applicationId",
                  "applicationVersion",
                  "runtimeVersion",
                  "checkedAgainstRuntime",
                  "signature",
                  "verdict"
                ]
              },
              {
                "type": "null"
              }
            ]
          }
        }
      }
    },
    {
      "if": {
        "type": "object",
        "properties": {
          "operation": {
            "const": "bundle.sign"
          }
        },
        "required": [
          "operation"
        ]
      },
      "then": {
        "type": "object",
        "properties": {
          "data": {
            "oneOf": [
              {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                  "bundleSha256": {
                    "type": "string",
                    "pattern": "^[a-f0-9]{64}$"
                  },
                  "signaturePath": {
                    "type": "string",
                    "minLength": 1,
                    "maxLength": 4096
                  },
                  "publicKeySha256": {
                    "type": "string",
                    "pattern": "^[a-f0-9]{64}$"
                  }
                },
                "required": [
                  "bundleSha256",
                  "signaturePath",
                  "publicKeySha256"
                ]
              },
              {
                "type": "null"
              }
            ]
          }
        }
      }
    },
    {
      "if": {
        "type": "object",
        "properties": {
          "operation": {
            "const": "deploy.dry-run"
          }
        },
        "required": [
          "operation"
        ]
      },
      "then": {
        "type": "object",
        "properties": {
          "data": {
            "oneOf": [
              {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                  "bundleSha256": {
                    "type": "string",
                    "pattern": "^[a-f0-9]{64}$"
                  },
                  "plan": {
                    "$ref": "#/$defs/plan"
                  },
                  "planDigest": {
                    "type": "string",
                    "pattern": "^[a-f0-9]{64}$"
                  },
                  "environmentRevision": {
                    "type": "integer",
                    "minimum": 0,
                    "maximum": 9007199254740991
                  },
                  "preparedAt": {
                    "type": "string",
                    "pattern": "^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](?:[.][0-9]{1,9})?Z$"
                  },
                  "expiresAt": {
                    "type": "string",
                    "pattern": "^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](?:[.][0-9]{1,9})?Z$"
                  },
                  "planRecordPath": {
                    "type": "string",
                    "minLength": 1,
                    "maxLength": 4096
                  }
                },
                "required": [
                  "bundleSha256",
                  "plan",
                  "planDigest",
                  "environmentRevision",
                  "preparedAt",
                  "expiresAt",
                  "planRecordPath"
                ]
              },
              {
                "type": "null"
              }
            ]
          }
        }
      }
    },
    {
      "if": {
        "type": "object",
        "properties": {
          "operation": {
            "const": "deploy"
          }
        },
        "required": [
          "operation"
        ]
      },
      "then": {
        "type": "object",
        "properties": {
          "data": {
            "oneOf": [
              {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                  "bundleSha256": {
                    "type": "string",
                    "pattern": "^[a-f0-9]{64}$"
                  },
                  "deploymentId": {
                    "type": "string",
                    "pattern": "^[a-z0-9-]{1,64}$"
                  },
                  "planDigest": {
                    "type": "string",
                    "pattern": "^[a-f0-9]{64}$"
                  },
                  "environmentRevision": {
                    "type": "integer",
                    "minimum": 0,
                    "maximum": 9007199254740991
                  },
                  "status": {
                    "enum": [
                      "stopped",
                      "refused"
                    ]
                  }
                },
                "required": [
                  "bundleSha256",
                  "deploymentId",
                  "planDigest",
                  "environmentRevision",
                  "status"
                ]
              },
              {
                "type": "null"
              }
            ]
          }
        }
      }
    },
    {
      "if": {
        "type": "object",
        "properties": {
          "operation": {
            "const": "export"
          }
        },
        "required": [
          "operation"
        ]
      },
      "then": {
        "type": "object",
        "properties": {
          "data": {
            "oneOf": [
              {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                  "deploymentId": {
                    "type": "string",
                    "pattern": "^[a-z0-9-]{1,64}$"
                  },
                  "outputPath": {
                    "type": "string",
                    "minLength": 1,
                    "maxLength": 4096
                  },
                  "sha256": {
                    "type": "string",
                    "pattern": "^[a-f0-9]{64}$"
                  },
                  "ciphertextSha256": {
                    "type": "string",
                    "pattern": "^[a-f0-9]{64}$"
                  },
                  "ciphertextSize": {
                    "type": "integer",
                    "minimum": 0,
                    "maximum": 9007199254740991
                  },
                  "fenceEpoch": {
                    "type": "integer",
                    "minimum": 0,
                    "maximum": 9007199254740991
                  },
                  "sourceState": {
                    "const": "fenced"
                  },
                  "excludedDataCategories": {
                    "type": "array",
                    "items": {
                      "type": "string",
                      "maxLength": 64
                    },
                    "uniqueItems": true
                  },
                  "recovery": {
                    "type": "string",
                    "maxLength": 2048
                  }
                },
                "required": [
                  "deploymentId",
                  "outputPath",
                  "sha256",
                  "ciphertextSha256",
                  "ciphertextSize",
                  "fenceEpoch",
                  "sourceState",
                  "excludedDataCategories",
                  "recovery"
                ]
              },
              {
                "type": "null"
              }
            ]
          }
        }
      }
    },
    {
      "if": {
        "type": "object",
        "properties": {
          "operation": {
            "const": "import.dry-run"
          }
        },
        "required": [
          "operation"
        ]
      },
      "then": {
        "type": "object",
        "properties": {
          "data": {
            "oneOf": [
              {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                  "bundleSha256": {
                    "type": "string",
                    "pattern": "^[a-f0-9]{64}$"
                  },
                  "eligible": {
                    "type": "boolean"
                  },
                  "applicationId": {
                    "type": "string",
                    "pattern": "^[a-z][a-z0-9-]{0,62}$"
                  },
                  "applicationVersion": {
                    "type": "string",
                    "maxLength": 128,
                    "pattern": "^(0|[1-9][0-9]*)[.](0|[1-9][0-9]*)[.](0|[1-9][0-9]*)(?:-(?:0|[1-9][0-9]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*)(?:[.](?:0|[1-9][0-9]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*))*)?$"
                  },
                  "sourceRuntime": {
                    "type": "string",
                    "maxLength": 128,
                    "pattern": "^(0|[1-9][0-9]*)[.](0|[1-9][0-9]*)[.](0|[1-9][0-9]*)(?:-(?:0|[1-9][0-9]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*)(?:[.](?:0|[1-9][0-9]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*))*)?$"
                  },
                  "schemaHead": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                      "platform": {
                        "type": "string",
                        "pattern": "^[0-9]{4}_[a-z0-9_]{1,120}$"
                      },
                      "product": {
                        "type": "string",
                        "pattern": "^[a-f0-9]{64}$"
                      }
                    },
                    "required": [
                      "platform",
                      "product"
                    ]
                  },
                  "fenceEpoch": {
                    "type": "integer",
                    "minimum": 0,
                    "maximum": 9007199254740991
                  },
                  "workflowSystemDatabase": {
                    "enum": [
                      "included",
                      "absent"
                    ]
                  },
                  "blockers": {
                    "type": "array",
                    "items": {
                      "$ref": "#/$defs/error"
                    }
                  }
                },
                "required": [
                  "bundleSha256",
                  "eligible",
                  "applicationId",
                  "applicationVersion",
                  "sourceRuntime",
                  "schemaHead",
                  "fenceEpoch",
                  "workflowSystemDatabase",
                  "blockers"
                ]
              },
              {
                "type": "null"
              }
            ]
          }
        }
      }
    },
    {
      "if": {
        "type": "object",
        "properties": {
          "operation": {
            "const": "import"
          }
        },
        "required": [
          "operation"
        ]
      },
      "then": {
        "type": "object",
        "properties": {
          "data": {
            "oneOf": [
              {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                  "bundleSha256": {
                    "type": "string",
                    "pattern": "^[a-f0-9]{64}$"
                  },
                  "deploymentId": {
                    "type": "string",
                    "pattern": "^[a-z0-9-]{1,64}$"
                  },
                  "status": {
                    "const": "ready-for-cutover"
                  },
                  "applicationDigest": {
                    "type": "string",
                    "pattern": "^[a-f0-9]{64}$"
                  },
                  "schemaHead": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                      "platform": {
                        "type": "string",
                        "pattern": "^[0-9]{4}_[a-z0-9_]{1,120}$"
                      },
                      "product": {
                        "type": "string",
                        "pattern": "^[a-f0-9]{64}$"
                      }
                    },
                    "required": [
                      "platform",
                      "product"
                    ]
                  },
                  "verification": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                      "checksums": {
                        "const": "match"
                      },
                      "tableCounts": {
                        "const": "match"
                      },
                      "objects": {
                        "const": "match"
                      },
                      "referenceIntegrity": {
                        "const": "match"
                      }
                    },
                    "required": [
                      "checksums",
                      "tableCounts",
                      "objects",
                      "referenceIntegrity"
                    ]
                  },
                  "credentialReset": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                      "sessions": {
                        "const": "reset"
                      },
                      "apiKeys": {
                        "const": "reset"
                      },
                      "invites": {
                        "const": "reset"
                      },
                      "oidcArtifacts": {
                        "const": "reset"
                      },
                      "passwordHashes": {
                        "enum": [
                          "preserved",
                          "reset"
                        ]
                      },
                      "forcedLogin": {
                        "type": "boolean"
                      }
                    },
                    "required": [
                      "sessions",
                      "apiKeys",
                      "invites",
                      "oidcArtifacts",
                      "passwordHashes",
                      "forcedLogin"
                    ]
                  }
                },
                "required": [
                  "bundleSha256",
                  "deploymentId",
                  "status",
                  "applicationDigest",
                  "schemaHead",
                  "verification",
                  "credentialReset"
                ]
              },
              {
                "type": "null"
              }
            ]
          }
        }
      }
    },
    {
      "if": {
        "type": "object",
        "properties": {
          "operation": {
            "const": "resume"
          }
        },
        "required": [
          "operation"
        ]
      },
      "then": {
        "type": "object",
        "properties": {
          "data": {
            "oneOf": [
              {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                  "deploymentId": {
                    "type": "string",
                    "pattern": "^[a-z0-9-]{1,64}$"
                  },
                  "fenceEpoch": {
                    "type": "integer",
                    "minimum": 0,
                    "maximum": 9007199254740991
                  },
                  "released": {
                    "type": "boolean"
                  },
                  "environmentRevision": {
                    "type": "integer",
                    "minimum": 0,
                    "maximum": 9007199254740991
                  }
                },
                "required": [
                  "deploymentId",
                  "fenceEpoch",
                  "released",
                  "environmentRevision"
                ]
              },
              {
                "type": "null"
              }
            ]
          }
        }
      }
    },
    {
      "if": {
        "type": "object",
        "properties": {
          "operation": {
            "const": "runtime.inspect"
          }
        },
        "required": [
          "operation"
        ]
      },
      "then": {
        "type": "object",
        "properties": {
          "data": {
            "oneOf": [
              {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                  "runtimeVersion": {
                    "type": "string",
                    "maxLength": 128,
                    "pattern": "^(0|[1-9][0-9]*)[.](0|[1-9][0-9]*)[.](0|[1-9][0-9]*)(?:-(?:0|[1-9][0-9]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*)(?:[.](?:0|[1-9][0-9]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*))*)?$"
                  },
                  "target": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                      "os": {
                        "type": "string",
                        "pattern": "^[a-z][a-z0-9]{0,15}$"
                      },
                      "arch": {
                        "type": "string",
                        "pattern": "^[a-z][a-z0-9_]{0,15}$"
                      },
                      "nodeMajor": {
                        "type": "integer",
                        "minimum": 1,
                        "maximum": 999
                      }
                    },
                    "required": [
                      "os",
                      "arch",
                      "nodeMajor"
                    ]
                  },
                  "nodeVersion": {
                    "type": "string",
                    "pattern": "^[0-9]+[.][0-9]+[.][0-9]+$"
                  },
                  "contractVersion": {
                    "const": "1.0.0-draft.2"
                  },
                  "capabilityVocabularyVersion": {
                    "const": 1
                  },
                  "capabilities": {
                    "type": "array",
                    "items": {
                      "type": "string",
                      "maxLength": 64,
                      "pattern": "^[a-z][a-z0-9]*(?:[-_][a-z0-9]+)*$"
                    },
                    "uniqueItems": true
                  },
                  "executionLevels": {
                    "type": "array",
                    "items": {
                      "enum": [
                        "none",
                        "in-process"
                      ]
                    },
                    "uniqueItems": true,
                    "minItems": 1
                  },
                  "schemaHead": {
                    "oneOf": [
                      {
                        "type": "object",
                        "additionalProperties": false,
                        "properties": {
                          "platform": {
                            "type": "string",
                            "pattern": "^[0-9]{4}_[a-z0-9_]{1,120}$"
                          },
                          "product": {
                            "type": "string",
                            "pattern": "^[a-f0-9]{64}$"
                          }
                        },
                        "required": [
                          "platform",
                          "product"
                        ]
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "applicationId": {
                    "oneOf": [
                      {
                        "type": "string",
                        "pattern": "^[a-z][a-z0-9-]{0,62}$"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "applicationVersion": {
                    "oneOf": [
                      {
                        "type": "string",
                        "maxLength": 128,
                        "pattern": "^(0|[1-9][0-9]*)[.](0|[1-9][0-9]*)[.](0|[1-9][0-9]*)(?:-(?:0|[1-9][0-9]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*)(?:[.](?:0|[1-9][0-9]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*))*)?$"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "applicationDigest": {
                    "oneOf": [
                      {
                        "type": "string",
                        "pattern": "^[a-f0-9]{64}$"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "releaseManifestSha256": {
                    "oneOf": [
                      {
                        "type": "string",
                        "pattern": "^[a-f0-9]{64}$"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "managedPosture": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                      "supported": {
                        "type": "boolean"
                      },
                      "receiptSha256": {
                        "oneOf": [
                          {
                            "type": "string",
                            "pattern": "^[a-f0-9]{64}$"
                          },
                          {
                            "type": "null"
                          }
                        ]
                      }
                    },
                    "required": [
                      "supported",
                      "receiptSha256"
                    ]
                  },
                  "fence": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                      "state": {
                        "enum": [
                          "open",
                          "fenced"
                        ]
                      },
                      "fenceEpoch": {
                        "type": "integer",
                        "minimum": 0,
                        "maximum": 9007199254740991
                      }
                    },
                    "required": [
                      "state",
                      "fenceEpoch"
                    ]
                  },
                  "environmentRevision": {
                    "type": "integer",
                    "minimum": 0,
                    "maximum": 9007199254740991
                  }
                },
                "required": [
                  "runtimeVersion",
                  "target",
                  "nodeVersion",
                  "contractVersion",
                  "capabilityVocabularyVersion",
                  "capabilities",
                  "executionLevels",
                  "schemaHead",
                  "applicationId",
                  "applicationVersion",
                  "applicationDigest",
                  "releaseManifestSha256",
                  "managedPosture",
                  "fence",
                  "environmentRevision"
                ]
              },
              {
                "type": "null"
              }
            ]
          }
        }
      }
    },
    {
      "if": {
        "type": "object",
        "properties": {
          "operation": {
            "const": "runtime.prepare"
          }
        },
        "required": [
          "operation"
        ]
      },
      "then": {
        "type": "object",
        "properties": {
          "data": {
            "oneOf": [
              {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                  "plan": {
                    "$ref": "#/$defs/plan"
                  },
                  "planDigest": {
                    "type": "string",
                    "pattern": "^[a-f0-9]{64}$"
                  },
                  "preparedAt": {
                    "type": "string",
                    "pattern": "^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](?:[.][0-9]{1,9})?Z$"
                  },
                  "expiresAt": {
                    "type": "string",
                    "pattern": "^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](?:[.][0-9]{1,9})?Z$"
                  },
                  "environmentRevision": {
                    "type": "integer",
                    "minimum": 0,
                    "maximum": 9007199254740991
                  }
                },
                "required": [
                  "plan",
                  "planDigest",
                  "preparedAt",
                  "expiresAt",
                  "environmentRevision"
                ]
              },
              {
                "type": "null"
              }
            ]
          }
        }
      }
    },
    {
      "if": {
        "type": "object",
        "properties": {
          "operation": {
            "const": "runtime.quiesce"
          }
        },
        "required": [
          "operation"
        ]
      },
      "then": {
        "type": "object",
        "properties": {
          "data": {
            "oneOf": [
              {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                  "fenceEpoch": {
                    "type": "integer",
                    "minimum": 0,
                    "maximum": 9007199254740991
                  },
                  "status": {
                    "enum": [
                      "fenced",
                      "timed-out"
                    ]
                  },
                  "producers": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "additionalProperties": false,
                      "properties": {
                        "producer": {
                          "type": "string",
                          "maxLength": 128
                        },
                        "state": {
                          "enum": [
                            "stopped",
                            "drained",
                            "still-running"
                          ]
                        }
                      },
                      "required": [
                        "producer",
                        "state"
                      ]
                    }
                  },
                  "barriers": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "additionalProperties": false,
                      "properties": {
                        "barrier": {
                          "enum": [
                            "database-write-role",
                            "database-stopped-source",
                            "object-writes"
                          ]
                        },
                        "state": {
                          "enum": [
                            "held",
                            "unavailable"
                          ]
                        }
                      },
                      "required": [
                        "barrier",
                        "state"
                      ]
                    }
                  },
                  "unfencedExternal": {
                    "type": "array",
                    "items": {
                      "type": "string",
                      "maxLength": 256
                    }
                  }
                },
                "required": [
                  "fenceEpoch",
                  "status",
                  "producers",
                  "barriers",
                  "unfencedExternal"
                ]
              },
              {
                "type": "null"
              }
            ]
          }
        }
      }
    },
    {
      "if": {
        "type": "object",
        "properties": {
          "operation": {
            "const": "runtime.snapshot"
          }
        },
        "required": [
          "operation"
        ]
      },
      "then": {
        "type": "object",
        "properties": {
          "data": {
            "oneOf": [
              {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                  "migrationBundleSha256": {
                    "type": "string",
                    "pattern": "^[a-f0-9]{64}$"
                  },
                  "ciphertextSha256": {
                    "type": "string",
                    "pattern": "^[a-f0-9]{64}$"
                  },
                  "ciphertextSize": {
                    "type": "integer",
                    "minimum": 0,
                    "maximum": 9007199254740991
                  },
                  "sourceLedger": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                      "fenceEpoch": {
                        "type": "integer",
                        "minimum": 0,
                        "maximum": 9007199254740991
                      },
                      "schemaHead": {
                        "type": "object",
                        "additionalProperties": false,
                        "properties": {
                          "platform": {
                            "type": "string",
                            "pattern": "^[0-9]{4}_[a-z0-9_]{1,120}$"
                          },
                          "product": {
                            "type": "string",
                            "pattern": "^[a-f0-9]{64}$"
                          }
                        },
                        "required": [
                          "platform",
                          "product"
                        ]
                      },
                      "applicationDigest": {
                        "type": "string",
                        "pattern": "^[a-f0-9]{64}$"
                      },
                      "tableCounts": {
                        "type": "array",
                        "items": {
                          "type": "object",
                          "additionalProperties": false,
                          "properties": {
                            "database": {
                              "enum": [
                                "application",
                                "workflow-system"
                              ]
                            },
                            "schema": {
                              "type": "string",
                              "pattern": "^[a-z_][a-z0-9_]{0,62}$"
                            },
                            "table": {
                              "type": "string",
                              "pattern": "^[a-z_][a-z0-9_]{0,62}$"
                            },
                            "rows": {
                              "type": "integer",
                              "minimum": 0,
                              "maximum": 9007199254740991
                            }
                          },
                          "required": [
                            "database",
                            "schema",
                            "table",
                            "rows"
                          ]
                        },
                        "maxItems": 10000
                      },
                      "objectCount": {
                        "type": "integer",
                        "minimum": 0,
                        "maximum": 9007199254740991
                      },
                      "excludedDataCategories": {
                        "type": "array",
                        "items": {
                          "type": "string",
                          "maxLength": 64
                        },
                        "uniqueItems": true
                      }
                    },
                    "required": [
                      "fenceEpoch",
                      "schemaHead",
                      "applicationDigest",
                      "tableCounts",
                      "objectCount",
                      "excludedDataCategories"
                    ]
                  }
                },
                "required": [
                  "migrationBundleSha256",
                  "ciphertextSha256",
                  "ciphertextSize",
                  "sourceLedger"
                ]
              },
              {
                "type": "null"
              }
            ]
          }
        }
      }
    },
    {
      "if": {
        "type": "object",
        "properties": {
          "operation": {
            "const": "runtime.apply"
          }
        },
        "required": [
          "operation"
        ]
      },
      "then": {
        "type": "object",
        "properties": {
          "data": {
            "oneOf": [
              {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                  "status": {
                    "enum": [
                      "applied",
                      "already-applied"
                    ]
                  },
                  "environmentRevision": {
                    "type": "integer",
                    "minimum": 0,
                    "maximum": 9007199254740991
                  },
                  "receipts": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "additionalProperties": false,
                      "properties": {
                        "step": {
                          "type": "string",
                          "maxLength": 128
                        },
                        "state": {
                          "enum": [
                            "done",
                            "skipped"
                          ]
                        },
                        "startedAt": {
                          "type": "string",
                          "pattern": "^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](?:[.][0-9]{1,9})?Z$"
                        },
                        "finishedAt": {
                          "type": "string",
                          "pattern": "^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](?:[.][0-9]{1,9})?Z$"
                        },
                        "digest": {
                          "oneOf": [
                            {
                              "type": "string",
                              "pattern": "^[a-f0-9]{64}$"
                            },
                            {
                              "type": "null"
                            }
                          ]
                        }
                      },
                      "required": [
                        "step",
                        "state",
                        "startedAt",
                        "finishedAt",
                        "digest"
                      ]
                    }
                  }
                },
                "required": [
                  "status",
                  "environmentRevision",
                  "receipts"
                ]
              },
              {
                "type": "null"
              }
            ]
          }
        }
      }
    },
    {
      "if": {
        "type": "object",
        "properties": {
          "operation": {
            "const": "runtime.health"
          }
        },
        "required": [
          "operation"
        ]
      },
      "then": {
        "type": "object",
        "properties": {
          "data": {
            "oneOf": [
              {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                  "live": {
                    "type": "boolean"
                  },
                  "ready": {
                    "type": "boolean"
                  },
                  "checks": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "additionalProperties": false,
                      "properties": {
                        "name": {
                          "enum": [
                            "database",
                            "schema",
                            "bindings",
                            "assets",
                            "worker",
                            "workflow-system-database"
                          ]
                        },
                        "ok": {
                          "type": "boolean"
                        },
                        "detail": {
                          "oneOf": [
                            {
                              "type": "string",
                              "maxLength": 512
                            },
                            {
                              "type": "null"
                            }
                          ]
                        }
                      },
                      "required": [
                        "name",
                        "ok",
                        "detail"
                      ]
                    }
                  }
                },
                "required": [
                  "live",
                  "ready",
                  "checks"
                ]
              },
              {
                "type": "null"
              }
            ]
          }
        }
      }
    },
    {
      "if": {
        "type": "object",
        "properties": {
          "operation": {
            "const": "runtime.resume"
          }
        },
        "required": [
          "operation"
        ]
      },
      "then": {
        "type": "object",
        "properties": {
          "data": {
            "oneOf": [
              {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                  "fenceEpoch": {
                    "type": "integer",
                    "minimum": 0,
                    "maximum": 9007199254740991
                  },
                  "released": {
                    "type": "boolean"
                  },
                  "environmentRevision": {
                    "type": "integer",
                    "minimum": 0,
                    "maximum": 9007199254740991
                  }
                },
                "required": [
                  "fenceEpoch",
                  "released",
                  "environmentRevision"
                ]
              },
              {
                "type": "null"
              }
            ]
          }
        }
      }
    },
    {
      "if": {
        "type": "object",
        "properties": {
          "operation": {
            "enum": [
              "init",
              "doctor",
              "plan",
              "openapi",
              "gen-handler",
              "deploy.legacy",
              "tenant.ensure",
              "dev.gen-secrets",
              "dev.db",
              "dev.bootstrap-tenant",
              "version",
              "help"
            ]
          }
        },
        "required": [
          "operation"
        ]
      },
      "then": {
        "type": "object",
        "properties": {
          "data": {
            "type": [
              "object",
              "null"
            ]
          }
        }
      }
    },
    {
      "if": {
        "type": "object",
        "properties": {
          "ok": {
            "const": true
          }
        },
        "required": [
          "ok"
        ]
      },
      "then": {
        "type": "object",
        "properties": {
          "errors": {
            "type": "array",
            "maxItems": 0
          }
        }
      },
      "else": {
        "type": "object",
        "properties": {
          "errors": {
            "type": "array",
            "minItems": 1
          }
        }
      }
    }
  ],
  "$defs": {
    "error": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "code": {
          "type": "string",
          "pattern": "^(RAY|SPEC)_[A-Z0-9_]+$"
        },
        "reason": {
          "type": "string",
          "pattern": "^[a-z0-9]+(?:-[a-z0-9]+)*$"
        },
        "path": {
          "type": "string",
          "maxLength": 4096
        },
        "message": {
          "type": "string",
          "maxLength": 2048
        },
        "retryable": {
          "type": "boolean"
        }
      },
      "required": [
        "code",
        "message",
        "retryable"
      ]
    },
    "warning": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "code": {
          "type": "string",
          "pattern": "^(RAY_W|SPEC)_[A-Z0-9_]+$"
        },
        "path": {
          "type": "string",
          "maxLength": 4096
        },
        "message": {
          "type": "string",
          "maxLength": 2048
        }
      },
      "required": [
        "code",
        "message"
      ]
    },
    "plan": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "bundleSha256": {
          "type": "string",
          "pattern": "^[a-f0-9]{64}$"
        },
        "applicationId": {
          "type": "string",
          "pattern": "^[a-z][a-z0-9-]{0,62}$"
        },
        "applicationVersion": {
          "type": "string",
          "maxLength": 128,
          "pattern": "^(0|[1-9][0-9]*)[.](0|[1-9][0-9]*)[.](0|[1-9][0-9]*)(?:-(?:0|[1-9][0-9]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*)(?:[.](?:0|[1-9][0-9]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*))*)?$"
        },
        "requiredBindings": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "name": {
                "type": "string",
                "pattern": "^[A-Z][A-Z0-9_]{0,127}$"
              },
              "kind": {
                "enum": [
                  "secret",
                  "config"
                ]
              },
              "required": {
                "type": "boolean"
              },
              "satisfied": {
                "type": "boolean"
              }
            },
            "required": [
              "name",
              "kind",
              "required",
              "satisfied"
            ]
          },
          "maxItems": 256
        },
        "schemaImpact": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "from": {
              "oneOf": [
                {
                  "type": "object",
                  "additionalProperties": false,
                  "properties": {
                    "platform": {
                      "type": "string",
                      "pattern": "^[0-9]{4}_[a-z0-9_]{1,120}$"
                    },
                    "product": {
                      "type": "string",
                      "pattern": "^[a-f0-9]{64}$"
                    }
                  },
                  "required": [
                    "platform",
                    "product"
                  ]
                },
                {
                  "type": "null"
                }
              ]
            },
            "to": {
              "type": "object",
              "additionalProperties": false,
              "properties": {
                "platform": {
                  "type": "string",
                  "pattern": "^[0-9]{4}_[a-z0-9_]{1,120}$"
                },
                "product": {
                  "type": "string",
                  "pattern": "^[a-f0-9]{64}$"
                }
              },
              "required": [
                "platform",
                "product"
              ]
            },
            "productDeltaSha256": {
              "oneOf": [
                {
                  "type": "string",
                  "pattern": "^[a-f0-9]{64}$"
                },
                {
                  "type": "null"
                }
              ]
            },
            "destructive": {
              "type": "boolean"
            },
            "allowlisted": {
              "type": "boolean"
            }
          },
          "required": [
            "from",
            "to",
            "productDeltaSha256",
            "destructive",
            "allowlisted"
          ]
        },
        "permissionChanges": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "executionFrom": {
              "enum": [
                "none",
                "in-process",
                "sandboxed",
                null
              ]
            },
            "executionTo": {
              "enum": [
                "none",
                "in-process",
                "sandboxed"
              ]
            },
            "egressAdded": {
              "type": "array",
              "items": {
                "type": "string",
                "maxLength": 253
              },
              "uniqueItems": true
            },
            "egressRemoved": {
              "type": "array",
              "items": {
                "type": "string",
                "maxLength": 253
              },
              "uniqueItems": true
            },
            "capabilitiesAdded": {
              "type": "array",
              "items": {
                "type": "string",
                "maxLength": 64,
                "pattern": "^[a-z][a-z0-9]*(?:[-_][a-z0-9]+)*$"
              },
              "uniqueItems": true
            },
            "capabilitiesRemoved": {
              "type": "array",
              "items": {
                "type": "string",
                "maxLength": 64,
                "pattern": "^[a-z][a-z0-9]*(?:[-_][a-z0-9]+)*$"
              },
              "uniqueItems": true
            }
          },
          "required": [
            "executionFrom",
            "executionTo",
            "egressAdded",
            "egressRemoved",
            "capabilitiesAdded",
            "capabilitiesRemoved"
          ]
        },
        "storageRequirements": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "bundleBytes": {
              "type": "integer",
              "minimum": 0,
              "maximum": 9007199254740991
            },
            "extractedBytes": {
              "type": "integer",
              "minimum": 0,
              "maximum": 9007199254740991
            }
          },
          "required": [
            "bundleBytes",
            "extractedBytes"
          ]
        },
        "blockers": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/error"
          }
        },
        "warnings": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/warning"
          }
        }
      },
      "required": [
        "bundleSha256",
        "applicationId",
        "applicationVersion",
        "requiredBindings",
        "schemaImpact",
        "permissionChanges",
        "storageRequirements",
        "blockers",
        "warnings"
      ]
    }
  }
};

/** contract/reserved-bindings.json#/bindingsFile/schema */
export const BINDINGS_FILE_SCHEMA: Readonly<Record<string, unknown>> = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "urn:rayspec:bindings-file:v1",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "bindingsFormatVersion": {
      "const": 1
    },
    "bindings": {
      "type": "array",
      "maxItems": 256,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "name": {
            "type": "string",
            "pattern": "^[A-Z][A-Z0-9_]{0,127}$"
          },
          "value": {
            "type": "string",
            "maxLength": 65536
          }
        },
        "required": [
          "name",
          "value"
        ]
      }
    }
  },
  "required": [
    "bindingsFormatVersion",
    "bindings"
  ]
};
